select
	 [PriceListDetailID] = concat('"', [PriceListDetail].[PriceListDetailID], '"'),
	 [PriceListID] = concat('"', [PriceListDetail].[PriceListID], '"'),
	 [ItemID] = concat('"', [PriceListDetail].[ItemID], '"'),
	 [Type] = concat('"', [PriceListDetail].[Type], '"'),
	 [CalculatedFromPriceListID] = concat('"', [PriceListDetail].[CalculatedFromPriceListID], '"'),
	 [CalculatedExchangeRate] = concat('"', [PriceListDetail].[CalculatedExchangeRate], '"'),
	 [CalculatedDate] = convert(varchar(50), [PriceListDetail].[CalculatedDate], 21),
	 [Rate] = concat('"', [PriceListDetail].[Rate], '"'),
	 [WarrantyRate] = concat('"', [PriceListDetail].[WarrantyRate], '"'),
	 [IsQuotable] = concat('"', [PriceListDetail].[IsQuotable], '"'),
	 [IsSupported] = concat('"', [PriceListDetail].[IsSupported], '"'),
	 [IsPricingReviewRequired] = concat('"', [PriceListDetail].[IsPricingReviewRequired], '"'),
	 [IsBomRequired] = concat('"', [PriceListDetail].[IsBomRequired], '"'),
	 [IsConfigPriced] = concat('"', [PriceListDetail].[IsConfigPriced], '"'),
	 [OEMSupportEndDate] = convert(varchar(50), [PriceListDetail].[OEMSupportEndDate], 21),
	 [OEMSupportCost] = concat('"', [PriceListDetail].[OEMSupportCost], '"'),
	 [IsBandedPricing] = concat('"', [PriceListDetail].[IsBandedPricing], '"'),
	 [PriceBandID] = concat('"', [PriceListDetail].[PriceBandID], '"'),
	 [IsExcludedFromBulkPriceUpdates] = concat('"', [PriceListDetail].[IsExcludedFromBulkPriceUpdates], '"'),
	 [PriceListItemMultiplier] = concat('"', [PriceListDetail].[PriceListItemMultiplier], '"'),
	 [LastUpdatedBy] = concat('"', [PriceListDetail].[LastUpdatedBy], '"'),
	 [LastUpdated] = convert(varchar(50), [PriceListDetail].[LastUpdated], 21),
	 [LastUpdatedByID] = concat('"', [PriceListDetail].[LastUpdatedByID], '"')
from ProductManagement.dbo.PriceListDetail