select
	 [PriceListDetailID] = concat(char(34), isNull(replace(cast([PriceListDetail].[PriceListDetailID] as nvarchar(max)), char(34), char(0)), '\N'), char(34)),
	 [PriceListID] = concat(char(34), isNull(replace(cast([PriceListDetail].[PriceListID] as nvarchar(max)), char(34), char(0)), '\N'), char(34)),
	 [ItemID] = concat(char(34), isNull(replace(cast([PriceListDetail].[ItemID] as nvarchar(max)), char(34), char(0)), '\N'), char(34)),
	 [Type] = concat(char(34), isNull(replace(cast([PriceListDetail].[Type] as nvarchar(max)), char(34), char(0)), '\N'), char(34)),
	 [CalculatedFromPriceListID] = concat(char(34), isNull(replace(cast([PriceListDetail].[CalculatedFromPriceListID] as nvarchar(max)), char(34), char(0)), '\N'), char(34)),
	 [CalculatedExchangeRate] = concat(char(34), isNull(replace(cast([PriceListDetail].[CalculatedExchangeRate] as nvarchar(max)), char(34), char(0)), '\N'), char(34)),
	 [CalculatedDate] = isNull(convert(varchar(50), [PriceListDetail].[CalculatedDate], 21), '\N'),
	 [Rate] = concat(char(34), isNull(replace(cast([PriceListDetail].[Rate] as nvarchar(max)), char(34), char(0)), '\N'), char(34)),
	 [WarrantyRate] = concat(char(34), isNull(replace(cast([PriceListDetail].[WarrantyRate] as nvarchar(max)), char(34), char(0)), '\N'), char(34)),
	 [IsQuotable] = concat(char(34), isNull(replace(cast([PriceListDetail].[IsQuotable] as nvarchar(max)), char(34), char(0)), '\N'), char(34)),
	 [IsSupported] = concat(char(34), isNull(replace(cast([PriceListDetail].[IsSupported] as nvarchar(max)), char(34), char(0)), '\N'), char(34)),
	 [IsPricingReviewRequired] = concat(char(34), isNull(replace(cast([PriceListDetail].[IsPricingReviewRequired] as nvarchar(max)), char(34), char(0)), '\N'), char(34)),
	 [IsBomRequired] = concat(char(34), isNull(replace(cast([PriceListDetail].[IsBomRequired] as nvarchar(max)), char(34), char(0)), '\N'), char(34)),
	 [IsConfigPriced] = concat(char(34), isNull(replace(cast([PriceListDetail].[IsConfigPriced] as nvarchar(max)), char(34), char(0)), '\N'), char(34)),
	 [OEMSupportEndDate] = isNull(convert(varchar(50), [PriceListDetail].[OEMSupportEndDate], 21), '\N'),
	 [OEMSupportCost] = concat(char(34), isNull(replace(cast([PriceListDetail].[OEMSupportCost] as nvarchar(max)), char(34), char(0)), '\N'), char(34)),
	 [IsBandedPricing] = concat(char(34), isNull(replace(cast([PriceListDetail].[IsBandedPricing] as nvarchar(max)), char(34), char(0)), '\N'), char(34)),
	 [PriceBandID] = concat(char(34), isNull(replace(cast([PriceListDetail].[PriceBandID] as nvarchar(max)), char(34), char(0)), '\N'), char(34)),
	 [IsExcludedFromBulkPriceUpdates] = concat(char(34), isNull(replace(cast([PriceListDetail].[IsExcludedFromBulkPriceUpdates] as nvarchar(max)), char(34), char(0)), '\N'), char(34)),
	 [PriceListItemMultiplier] = concat(char(34), isNull(replace(cast([PriceListDetail].[PriceListItemMultiplier] as nvarchar(max)), char(34), char(0)), '\N'), char(34)),
	 [LastUpdatedBy] = concat(char(34), isNull(replace(cast([PriceListDetail].[LastUpdatedBy] as nvarchar(max)), char(34), char(0)), '\N'), char(34)),
	 [LastUpdated] = isNull(convert(varchar(50), [PriceListDetail].[LastUpdated], 21), '\N'),
	 [LastUpdatedByID] = concat(char(34), isNull(replace(cast([PriceListDetail].[LastUpdatedByID] as nvarchar(max)), char(34), char(0)), '\N'), char(34))
from ProductManagement.dbo.PriceListDetail with(nolock)