select
	 [UnitGuid] = isNull(cast([tqoUnit].[UnitGuid] as varchar(36)), '\N'),
	 [CustomerID] = isNull(cast([tqoUnit].[CustomerID] as varchar(36)), '\N'),
	 [BOMGuid] = isNull(cast([tqoUnit].[BOMGuid] as varchar(36)), '\N'),
	 [BillToCustAddrGuid] = isNull(cast([tqoUnit].[BillToCustAddrGuid] as varchar(36)), '\N'),
	 [ShipToCustAddrGuid] = isNull(cast([tqoUnit].[ShipToCustAddrGuid] as varchar(36)), '\N'),
	 [MASSrvDealer] = isNull(cast([tqoUnit].[MASSrvDealer] as varchar(36)), '\N'),
	 [MASUnitStatKey] = isNull(cast([tqoUnit].[MASUnitStatKey] as varchar(36)), '\N'),
	 [HwPO_UserFld1] = concat(char(34), isNull(replace(cast([tqoUnit].[HwPO_UserFld1] as nvarchar(15)), char(34), char(0)), '\N'), char(34)),
	 [HwPOLine_UserFld2] = concat(char(34), isNull(replace(cast([tqoUnit].[HwPOLine_UserFld2] as nvarchar(15)), char(34), char(0)), '\N'), char(34)),
	 [SwSupportVendors_UserFld3] = concat(char(34), isNull(replace(cast([tqoUnit].[SwSupportVendors_UserFld3] as nvarchar(15)), char(34), char(0)), '\N'), char(34)),
	 [SwPO_UserFld4] = concat(char(34), isNull(replace(cast([tqoUnit].[SwPO_UserFld4] as nvarchar(15)), char(34), char(0)), '\N'), char(34)),
	 [SwPOLine_UserFld5] = concat(char(34), isNull(replace(cast([tqoUnit].[SwPOLine_UserFld5] as nvarchar(15)), char(34), char(0)), '\N'), char(34)),
	 [ChangedByID] = isNull(cast([tqoUnit].[ChangedByID] as varchar(36)), '\N'),
	 [LastChanged] = isNull(convert(varchar(50), [tqoUnit].[LastChanged], 21), '\N'),
	 [CreateByID] = isNull(cast([tqoUnit].[CreateByID] as varchar(36)), '\N'),
	 [CreateDate] = isNull(convert(varchar(50), [tqoUnit].[CreateDate], 21), '\N'),
	 [TopSerialNum] = concat(char(34), isNull(replace(cast([tqoUnit].[TopSerialNum] as nvarchar(50)), char(34), char(0)), '\N'), char(34)),
	 [TopShortDesc] = concat(char(34), isNull(replace(cast([tqoUnit].[TopShortDesc] as nvarchar(40)), char(34), char(0)), '\N'), char(34)),
	 [NodeName] = concat(char(34), isNull(replace(cast([tqoUnit].[NodeName] as nvarchar(50)), char(34), char(0)), '\N'), char(34)),
	 [PrevUnitGuid] = isNull(cast([tqoUnit].[PrevUnitGuid] as varchar(36)), '\N'),
	 [MASUnitKey] = isNull(cast([tqoUnit].[MASUnitKey] as varchar(36)), '\N'),
	 [WebModelCodeID] = isNull(cast([tqoUnit].[WebModelCodeID] as varchar(36)), '\N'),
	 [WebModelCode] = concat(char(34), isNull(replace(cast([tqoUnit].[WebModelCode] as nvarchar(50)), char(34), char(0)), '\N'), char(34)),
	 [FromAssetHeaderID] = isNull(cast([tqoUnit].[FromAssetHeaderID] as varchar(36)), '\N'),
	 [RecSource] = concat(char(34), isNull(replace(cast([tqoUnit].[RecSource] as nvarchar(50)), char(34), char(0)), '\N'), char(34))
from SinglePoint.dbo.tqoUnit with(nolock)