select
	 [UnitGuid] = concat(char(34), [tqoUnit].[UnitGuid], char(34)),
	 [CustomerID] = concat(char(34), [tqoUnit].[CustomerID], char(34)),
	 [BOMGuid] = concat(char(34), [tqoUnit].[BOMGuid], char(34)),
	 [BillToCustAddrGuid] = concat(char(34), [tqoUnit].[BillToCustAddrGuid], char(34)),
	 [ShipToCustAddrGuid] = concat(char(34), [tqoUnit].[ShipToCustAddrGuid], char(34)),
	 [MASSrvDealer] = concat(char(34), [tqoUnit].[MASSrvDealer], char(34)),
	 [MASUnitStatKey] = concat(char(34), [tqoUnit].[MASUnitStatKey], char(34)),
	 [HwPO_UserFld1] = concat(char(34), [tqoUnit].[HwPO_UserFld1], char(34)),
	 [HwPOLine_UserFld2] = concat(char(34), [tqoUnit].[HwPOLine_UserFld2], char(34)),
	 [SwSupportVendors_UserFld3] = concat(char(34), [tqoUnit].[SwSupportVendors_UserFld3], char(34)),
	 [SwPO_UserFld4] = concat(char(34), [tqoUnit].[SwPO_UserFld4], char(34)),
	 [SwPOLine_UserFld5] = concat(char(34), [tqoUnit].[SwPOLine_UserFld5], char(34)),
	 [ChangedByID] = concat(char(34), [tqoUnit].[ChangedByID], char(34)),
	 [LastChanged] = convert(varchar(50), [tqoUnit].[LastChanged], 21),
	 [CreateByID] = concat(char(34), [tqoUnit].[CreateByID], char(34)),
	 [CreateDate] = convert(varchar(50), [tqoUnit].[CreateDate], 21),
	 [TopSerialNum] = concat(char(34), [tqoUnit].[TopSerialNum], char(34)),
	 [TopShortDesc] = concat(char(34), [tqoUnit].[TopShortDesc], char(34)),
	 [NodeName] = concat(char(34), [tqoUnit].[NodeName], char(34)),
	 [PrevUnitGuid] = concat(char(34), [tqoUnit].[PrevUnitGuid], char(34)),
	 [MASUnitKey] = concat(char(34), [tqoUnit].[MASUnitKey], char(34)),
	 [WebModelCodeID] = concat(char(34), [tqoUnit].[WebModelCodeID], char(34)),
	 [WebModelCode] = concat(char(34), [tqoUnit].[WebModelCode], char(34)),
	 [FromAssetHeaderID] = concat(char(34), [tqoUnit].[FromAssetHeaderID], char(34)),
	 [RecSource] = concat(char(34), [tqoUnit].[RecSource], char(34))
from SinglePoint.dbo.tqoUnit