select
	 [BOMGuid] = concat('"', [tqoBOM].[BOMGuid], '"'),
	 [ItemGuid] = concat('"', [tqoBOM].[ItemGuid], '"'),
	 [ParentID] = concat('"', [tqoBOM].[ParentID], '"'),
	 [EvenCountFlag] = concat('"', [tqoBOM].[EvenCountFlag], '"'),
	 [MinQty] = concat('"', [tqoBOM].[MinQty], '"'),
	 [MaxQty] = concat('"', [tqoBOM].[MaxQty], '"'),
	 [StandardQty] = concat('"', [tqoBOM].[StandardQty], '"'),
	 [StandardFlag] = concat('"', [tqoBOM].[StandardFlag], '"'),
	 [RootItemGuid] = concat('"', [tqoBOM].[RootItemGuid], '"'),
	 [MASCompKey] = concat('"', [tqoBOM].[MASCompKey], '"'),
	 [MASParentKey] = concat('"', [tqoBOM].[MASParentKey], '"'),
	 [ChangedByID] = concat('"', [tqoBOM].[ChangedByID], '"'),
	 [LastChanged] = convert(varchar(50), [tqoBOM].[LastChanged], 21),
	 [CreateByID] = concat('"', [tqoBOM].[CreateByID], '"'),
	 [CreateDate] = convert(varchar(50), [tqoBOM].[CreateDate], 21),
	 [Source] = concat('"', [tqoBOM].[Source], '"'),
	 [SourceFKID] = concat('"', [tqoBOM].[SourceFKID], '"'),
	 [SparesKit] = concat('"', [tqoBOM].[SparesKit], '"'),
	 [SourceProc] = concat('"', [tqoBOM].[SourceProc], '"'),
	 [FromSiteAudit] = concat('"', [tqoBOM].[FromSiteAudit], '"')
from SinglePoint.dbo.tqoBOM