select
	 [NoteID] = concat(char(34), isNull(replace(cast([NotesGeneric].[NoteID] as nvarchar(max)), char(34), char(0)), '\N'), char(34)),
	 [FKID] = concat(char(34), isNull(replace(cast([NotesGeneric].[FKID] as nvarchar(max)), char(34), char(0)), '\N'), char(34)),
	 [ObjectType] = concat(char(34), isNull(replace(cast([NotesGeneric].[ObjectType] as nvarchar(max)), char(34), char(0)), '\N'), char(34)),
	 [Title] = concat(char(34), isNull(replace(cast([NotesGeneric].[Title] as nvarchar(max)), char(34), char(0)), '\N'), char(34)),
	 [Body] = concat(char(34), isNull(replace(cast([NotesGeneric].[Body] as nvarchar(max)), char(34), char(0)), '\N'), char(34)),
	 [Audiance] = concat(char(34), isNull(replace(cast([NotesGeneric].[Audiance] as nvarchar(max)), char(34), char(0)), '\N'), char(34)),
	 [EffectiveDate] = isNull(convert(varchar(50), [NotesGeneric].[EffectiveDate], 21), '\N'),
	 [ExpirationDate] = isNull(convert(varchar(50), [NotesGeneric].[ExpirationDate], 21), '\N'),
	 [Priority] = concat(char(34), isNull(replace(cast([NotesGeneric].[Priority] as nvarchar(max)), char(34), char(0)), '\N'), char(34)),
	 [CreatedByUserID] = concat(char(34), isNull(replace(cast([NotesGeneric].[CreatedByUserID] as nvarchar(max)), char(34), char(0)), '\N'), char(34)),
	 [CreatedDateUTC] = isNull(convert(varchar(50), [NotesGeneric].[CreatedDateUTC], 21), '\N'),
	 [LastUpdatedByUserID] = concat(char(34), isNull(replace(cast([NotesGeneric].[LastUpdatedByUserID] as nvarchar(max)), char(34), char(0)), '\N'), char(34)),
	 [LastUpdatedDateUTC] = isNull(convert(varchar(50), [NotesGeneric].[LastUpdatedDateUTC], 21), '\N'),
	 [AudianceCode] = concat(char(34), isNull(replace(cast([NotesGeneric].[AudianceCode] as nvarchar(max)), char(34), char(0)), '\N'), char(34)),
	 [Status] = concat(char(34), isNull(replace(cast([NotesGeneric].[Status] as nvarchar(max)), char(34), char(0)), '\N'), char(34)),
	 [CategoryID] = concat(char(34), isNull(replace(cast([NotesGeneric].[CategoryID] as nvarchar(max)), char(34), char(0)), '\N'), char(34)),
	 [Category] = concat(char(34), isNull(replace(cast([NotesGeneric].[Category] as nvarchar(max)), char(34), char(0)), '\N'), char(34)),
	 [ReferenceType] = concat(char(34), isNull(replace(cast([NotesGeneric].[ReferenceType] as nvarchar(max)), char(34), char(0)), '\N'), char(34)),
	 [ReferenceIdentifier] = concat(char(34), isNull(replace(cast([NotesGeneric].[ReferenceIdentifier] as nvarchar(max)), char(34), char(0)), '\N'), char(34))
from SinglePoint.dbo.NotesGeneric with(nolock)