select
	 [AddressID] = isNull(cast([AddressDetails].[AddressID] as varchar(36)), '\N'),
	 [WarehouseID] = isNull(cast([AddressDetails].[WarehouseID] as varchar(36)), '\N'),
	 [SalesTerritoryID] = isNull(cast([AddressDetails].[SalesTerritoryID] as varchar(36)), '\N'),
	 [TaxScheduleID] = isNull(cast([AddressDetails].[TaxScheduleID] as varchar(36)), '\N'),
	 [DefaultContactID] = isNull(cast([AddressDetails].[DefaultContactID] as varchar(36)), '\N'),
	 [ChangedByID] = isNull(cast([AddressDetails].[ChangedByID] as varchar(36)), '\N'),
	 [SalesPersonID] = isNull(cast([AddressDetails].[SalesPersonID] as varchar(36)), '\N'),
	 [LastChanged] = isNull(convert(varchar(50), [AddressDetails].[LastChanged], 21), '\N'),
	 [DrivingDistance_Miles] = isNull(cast([AddressDetails].[DrivingDistance_Miles] as varchar(36)), '\N'),
	 [DrivingTime_Minutes] = isNull(cast([AddressDetails].[DrivingTime_Minutes] as varchar(36)), '\N'),
	 [Driving_UpdateRequired] = isNull(cast([AddressDetails].[Driving_UpdateRequired] as varchar(36)), '\N'),
	 [AsyncStatus] = concat(char(34), isNull(replace(cast([AddressDetails].[AsyncStatus] as nvarchar(50)), char(34), char(0)), '\N'), char(34)),
	 [AsyncError] = concat(char(34), isNull(replace(cast([AddressDetails].[AsyncError] as nvarchar(255)), char(34), char(0)), '\N'), char(34)),
	 [CreateDate] = isNull(convert(varchar(50), [AddressDetails].[CreateDate], 21), '\N'),
	 [ServiceWarehouseID] = isNull(cast([AddressDetails].[ServiceWarehouseID] as varchar(36)), '\N'),
	 [TaxClass] = isNull(cast([AddressDetails].[TaxClass] as varchar(36)), '\N'),
	 [GenericAddressFlag] = isNull(cast([AddressDetails].[GenericAddressFlag] as varchar(36)), '\N'),
	 [GenericContactFlag] = isNull(cast([AddressDetails].[GenericContactFlag] as varchar(36)), '\N'),
	 [WarehouseCalculation_Method] = isNull(cast([AddressDetails].[WarehouseCalculation_Method] as varchar(36)), '\N'),
	 [WarehouseCalculation_Date] = isNull(convert(varchar(50), [AddressDetails].[WarehouseCalculation_Date], 21), '\N')
from SinglePoint.dbo.AddressDetails