select
	 [IncidentID] = isNull(cast([IncServiceOrders].[IncidentID] as varchar(36)), '\N'),
	 [ServiceOrderID] = isNull(cast([IncServiceOrders].[ServiceOrderID] as varchar(36)), '\N'),
	 [ServiceOrder_SAP_Key] = concat(char(34), isNull(replace(cast([IncServiceOrders].[ServiceOrder_SAP_Key] as nvarchar(18)), char(34), char(0)), '\N'), char(34)),
	 [Type] = concat(char(34), isNull(replace(cast([IncServiceOrders].[Type] as nvarchar(50)), char(34), char(0)), '\N'), char(34)),
	 [RequestDateTime] = isNull(convert(varchar(50), [IncServiceOrders].[RequestDateTime], 21), '\N'),
	 [AcknowledgedDateTime] = isNull(convert(varchar(50), [IncServiceOrders].[AcknowledgedDateTime], 21), '\N'),
	 [SAP_Plant_Key] = concat(char(34), isNull(replace(cast([IncServiceOrders].[SAP_Plant_Key] as nvarchar(18)), char(34), char(0)), '\N'), char(34)),
	 [SAP_Sold_To_Key] = concat(char(34), isNull(replace(cast([IncServiceOrders].[SAP_Sold_To_Key] as nvarchar(18)), char(34), char(0)), '\N'), char(34)),
	 [SAP_Ship_To_Key] = concat(char(34), isNull(replace(cast([IncServiceOrders].[SAP_Ship_To_Key] as nvarchar(18)), char(34), char(0)), '\N'), char(34)),
	 [SAP_Contract_Key] = concat(char(34), isNull(replace(cast([IncServiceOrders].[SAP_Contract_Key] as nvarchar(18)), char(34), char(0)), '\N'), char(34)),
	 [SAP_Contract_Line] = concat(char(34), isNull(replace(cast([IncServiceOrders].[SAP_Contract_Line] as nvarchar(18)), char(34), char(0)), '\N'), char(34)),
	 [SAP_Service_Material_Key] = concat(char(34), isNull(replace(cast([IncServiceOrders].[SAP_Service_Material_Key] as nvarchar(18)), char(34), char(0)), '\N'), char(34)),
	 [SAP_Equipment_Key] = concat(char(34), isNull(replace(cast([IncServiceOrders].[SAP_Equipment_Key] as nvarchar(18)), char(34), char(0)), '\N'), char(34)),
	 [Serial_Number] = concat(char(34), isNull(replace(cast([IncServiceOrders].[Serial_Number] as nvarchar(50)), char(34), char(0)), '\N'), char(34)),
	 [Sales_Organization] = concat(char(34), isNull(replace(cast([IncServiceOrders].[Sales_Organization] as nvarchar(50)), char(34), char(0)), '\N'), char(34)),
	 [Distribution_Channel] = concat(char(34), isNull(replace(cast([IncServiceOrders].[Distribution_Channel] as nvarchar(50)), char(34), char(0)), '\N'), char(34)),
	 [Division] = concat(char(34), isNull(replace(cast([IncServiceOrders].[Division] as nvarchar(50)), char(34), char(0)), '\N'), char(34)),
	 [CreateByID] = isNull(cast([IncServiceOrders].[CreateByID] as varchar(36)), '\N'),
	 [CreateDate] = isNull(convert(varchar(50), [IncServiceOrders].[CreateDate], 21), '\N'),
	 [Status] = concat(char(34), isNull(replace(cast([IncServiceOrders].[Status] as nvarchar(50)), char(34), char(0)), '\N'), char(34)),
	 [StatusMessage] = concat(char(34), isNull(replace(cast([IncServiceOrders].[StatusMessage] as nvarchar(max)), char(34), char(0)), '\N'), char(34)),
	 [ProblemDescription] = concat(char(34), isNull(replace(cast([IncServiceOrders].[ProblemDescription] as nvarchar(255)), char(34), char(0)), '\N'), char(34)),
	 [Requester] = concat(char(34), isNull(replace(cast([IncServiceOrders].[Requester] as nvarchar(50)), char(34), char(0)), '\N'), char(34)),
	 [PointOfContact] = concat(char(34), isNull(replace(cast([IncServiceOrders].[PointOfContact] as nvarchar(50)), char(34), char(0)), '\N'), char(34)),
	 [BatchID] = isNull(cast([IncServiceOrders].[BatchID] as varchar(36)), '\N'),
	 [BillToCustomerID] = isNull(cast([IncServiceOrders].[BillToCustomerID] as varchar(36)), '\N')
from SinglePoint.dbo.IncServiceOrders