select
	 [PartyInvolvedID] = concat(char(34), isNull(cast([PartiesInvolved].[PartyInvolvedID] as nvarchar(max)), '\N'), char(34)),
	 [FKID] = concat(char(34), isNull(cast([PartiesInvolved].[FKID] as nvarchar(max)), '\N'), char(34)),
	 [Type] = concat(char(34), isNull(cast([PartiesInvolved].[Type] as nvarchar(max)), '\N'), char(34)),
	 [IsPrimary] = concat(char(34), isNull(cast([PartiesInvolved].[IsPrimary] as nvarchar(max)), '\N'), char(34)),
	 [Name] = concat(char(34), isNull(cast([PartiesInvolved].[Name] as nvarchar(max)), '\N'), char(34)),
	 [InvolvementStart] = isNull(convert(varchar(50), [PartiesInvolved].[InvolvementStart], 21), '\N'),
	 [InvolvementEnd] = isNull(convert(varchar(50), [PartiesInvolved].[InvolvementEnd], 21), '\N'),
	 [Status] = concat(char(34), isNull(cast([PartiesInvolved].[Status] as nvarchar(max)), '\N'), char(34)),
	 [ID] = concat(char(34), isNull(cast([PartiesInvolved].[ID] as nvarchar(max)), '\N'), char(34)),
	 [PhonePrimary] = concat(char(34), isNull(cast([PartiesInvolved].[PhonePrimary] as nvarchar(max)), '\N'), char(34)),
	 [PhoneSecondary] = concat(char(34), isNull(cast([PartiesInvolved].[PhoneSecondary] as nvarchar(max)), '\N'), char(34)),
	 [EMail] = concat(char(34), isNull(cast([PartiesInvolved].[EMail] as nvarchar(max)), '\N'), char(34)),
	 [EMailMobile] = concat(char(34), isNull(cast([PartiesInvolved].[EMailMobile] as nvarchar(max)), '\N'), char(34)),
	 [Address] = concat(char(34), isNull(cast([PartiesInvolved].[Address] as nvarchar(max)), '\N'), char(34)),
	 [CreateByID] = concat(char(34), isNull(cast([PartiesInvolved].[CreateByID] as nvarchar(max)), '\N'), char(34)),
	 [CreateDate] = isNull(convert(varchar(50), [PartiesInvolved].[CreateDate], 21), '\N'),
	 [UpdateByID] = concat(char(34), isNull(cast([PartiesInvolved].[UpdateByID] as nvarchar(max)), '\N'), char(34)),
	 [UpdateDate] = isNull(convert(varchar(50), [PartiesInvolved].[UpdateDate], 21), '\N'),
	 [Notes] = concat(char(34), isNull(cast([PartiesInvolved].[Notes] as nvarchar(max)), '\N'), char(34)),
	 [IsNotificationRecipient] = concat(char(34), isNull(cast([PartiesInvolved].[IsNotificationRecipient] as nvarchar(max)), '\N'), char(34)),
	 [UserID] = concat(char(34), isNull(cast([PartiesInvolved].[UserID] as nvarchar(max)), '\N'), char(34)),
	 [PartyTypeID] = concat(char(34), isNull(cast([PartiesInvolved].[PartyTypeID] as nvarchar(max)), '\N'), char(34))
from SinglePoint.dbo.PartiesInvolved