select
	 [PartyInvolvedID] = quotename([Customer_PartiesInvolved].[PartyInvolvedID], char(34)),
	 [CustomerID] = quotename([Customer_PartiesInvolved].[CustomerID], char(34)),
	 [Type] = quotename([Customer_PartiesInvolved].[Type], char(34)),
	 [IsPrimary] = quotename([Customer_PartiesInvolved].[IsPrimary], char(34)),
	 [Name] = quotename([Customer_PartiesInvolved].[Name], char(34)),
	 [InvolvementStart] = convert(varchar(50), [Customer_PartiesInvolved].[InvolvementStart], 21),
	 [InvolvementEnd] = convert(varchar(50), [Customer_PartiesInvolved].[InvolvementEnd], 21),
	 [Status] = quotename([Customer_PartiesInvolved].[Status], char(34)),
	 [ID] = quotename([Customer_PartiesInvolved].[ID], char(34)),
	 [Phone_Primary] = quotename([Customer_PartiesInvolved].[Phone_Primary], char(34)),
	 [Phone_Secondary] = quotename([Customer_PartiesInvolved].[Phone_Secondary], char(34)),
	 [EMail] = quotename([Customer_PartiesInvolved].[EMail], char(34)),
	 [EMailMobile] = quotename([Customer_PartiesInvolved].[EMailMobile], char(34)),
	 [Address] = quotename([Customer_PartiesInvolved].[Address], char(34)),
	 [CreateByID] = quotename([Customer_PartiesInvolved].[CreateByID], char(34)),
	 [CreateDate] = convert(varchar(50), [Customer_PartiesInvolved].[CreateDate], 21),
	 [UpdateByID] = quotename([Customer_PartiesInvolved].[UpdateByID], char(34)),
	 [UpdateDate] = convert(varchar(50), [Customer_PartiesInvolved].[UpdateDate], 21),
	 [Notes] = quotename([Customer_PartiesInvolved].[Notes], char(34)),
	 [PartyTypeID] = quotename([Customer_PartiesInvolved].[PartyTypeID], char(34))
from SinglePoint.dbo.Customer_PartiesInvolved