select
	 [DispatchID] = isNull(cast([IncDispatch].[DispatchID] as varchar(36)), '\N'),
	 [IncidentID] = isNull(cast([IncDispatch].[IncidentID] as varchar(36)), '\N'),
	 [ProblemSummary] = concat(char(34), isNull(replace(cast([IncDispatch].[ProblemSummary] as nvarchar(255)), char(34), char(0)), '\N'), char(34)),
	 [SiteIdentifier] = concat(char(34), isNull(replace(cast([IncDispatch].[SiteIdentifier] as nvarchar(50)), char(34), char(0)), '\N'), char(34)),
	 [FieldEngineerName] = concat(char(34), isNull(replace(cast([IncDispatch].[FieldEngineerName] as nvarchar(50)), char(34), char(0)), '\N'), char(34)),
	 [ScheduledAppointment] = isNull(convert(varchar(50), [IncDispatch].[ScheduledAppointment], 21), '\N'),
	 [SiteVisitDate] = isNull(convert(varchar(50), [IncDispatch].[SiteVisitDate], 21), '\N'),
	 [NumberOfVisits] = isNull(cast([IncDispatch].[NumberOfVisits] as varchar(36)), '\N'),
	 [ExtendedTimeReason] = concat(char(34), isNull(replace(cast([IncDispatch].[ExtendedTimeReason] as nvarchar(255)), char(34), char(0)), '\N'), char(34)),
	 [WorkstreamID] = isNull(cast([IncDispatch].[WorkstreamID] as varchar(36)), '\N'),
	 [WorkstreamSlaID] = isNull(cast([IncDispatch].[WorkstreamSlaID] as varchar(36)), '\N'),
	 [isCustomerDefered] = isNull(cast([IncDispatch].[isCustomerDefered] as varchar(36)), '\N'),
	 [isSlaWaived] = isNull(cast([IncDispatch].[isSlaWaived] as varchar(36)), '\N'),
	 [isSlaMissed_SMS] = isNull(cast([IncDispatch].[isSlaMissed_SMS] as varchar(36)), '\N'),
	 [isSlaMissed_Customer] = isNull(cast([IncDispatch].[isSlaMissed_Customer] as varchar(36)), '\N'),
	 [isCancelled_Billable] = isNull(cast([IncDispatch].[isCancelled_Billable] as varchar(36)), '\N'),
	 [isCancelled_NonBillable] = isNull(cast([IncDispatch].[isCancelled_NonBillable] as varchar(36)), '\N'),
	 [CreateDate] = isNull(convert(varchar(50), [IncDispatch].[CreateDate], 21), '\N'),
	 [CreateUserID] = isNull(cast([IncDispatch].[CreateUserID] as varchar(36)), '\N'),
	 [LastUpdateDate] = isNull(convert(varchar(50), [IncDispatch].[LastUpdateDate], 21), '\N'),
	 [LastUpdateUserID] = isNull(cast([IncDispatch].[LastUpdateUserID] as varchar(36)), '\N'),
	 [StatusCodeID] = isNull(cast([IncDispatch].[StatusCodeID] as varchar(36)), '\N'),
	 [ReScheduledAppointment] = isNull(convert(varchar(50), [IncDispatch].[ReScheduledAppointment], 21), '\N')
from SinglePoint.dbo.IncDispatch