select
	 [CompanyGuid] = isNull(quotename([CompanyGuid], char(34)), '\N'),
	 [CompanyID] = isNull(quotename([CompanyID], char(34)), '\N'),
	 [CompanyName] = isNull(quotename([CompanyName], char(34)), '\N'),
	 [CreateDate] = isNull(convert(varchar(50), [CreateDate], 21), '\N'),
	 [MasterFlag] = isNull(quotename([MasterFlag], char(34)), '\N'),
	 [SAP_Company_Key] = isNull(quotename([SAP_Company_Key], char(34)), '\N'),
	 [SAP_Company_Code] = isNull(quotename([SAP_Company_Code], char(34)), '\N'),
	 [SAP_Sales_Org] = isNull(quotename([SAP_Sales_Org], char(34)), '\N'),
	 [SAP_Purch_Org] = isNull(quotename([SAP_Purch_Org], char(34)), '\N'),
	 [HomeCurrency] = isNull(quotename([HomeCurrency], char(34)), '\N'),
	 [Country] = isNull(quotename([Country], char(34)), '\N'),
	 [SAP_Vendor_Key] = isNull(quotename([SAP_Vendor_Key], char(34)), '\N'),
	 [WarehouseID_International] = isNull(quotename([WarehouseID_International], char(34)), '\N'),
	 [CustomerID_International] = isNull(quotename([CustomerID_International], char(34)), '\N'),
	 [SAP_International_EmployeeNumber] = isNull(quotename([SAP_International_EmployeeNumber], char(34)), '\N'),
	 [TaxCode] = isNull(quotename([TaxCode], char(34)), '\N'),
	 [TaxPct] = isNull(quotename([TaxPct], char(34)), '\N'),
	 [isQuotable] = isNull(quotename([isQuotable], char(34)), '\N'),
	 [MirrorTaxPct] = isNull(quotename([MirrorTaxPct], char(34)), '\N'),
	 [inERP] = isNull(quotename([inERP], char(34)), '\N'),
	 [inSinglePoint] = isNull(quotename([inSinglePoint], char(34)), '\N'),
	 [Oracle_Organization_ID] = isNull(quotename([Oracle_Organization_ID], char(34)), '\N'),
	 [ContractPrefix] = isNull(quotename([ContractPrefix], char(34)), '\N'),
	 [Default_PriceListID] = isNull(quotename([Default_PriceListID], char(34)), '\N'),
	 [canTransactServiceOrders] = isNull(quotename([canTransactServiceOrders], char(34)), '\N'),
	 [BillingAddressID] = isNull(quotename([BillingAddressID], char(34)), '\N')
from SinglePoint.dbo.tqoCompany