select
	 [WarehouseID] = concat('"', [WarehouseDetails].[WarehouseID], '"'),
	 [SegmentID] = concat('"', [WarehouseDetails].[SegmentID], '"'),
	 [WhseKey] = concat('"', [WarehouseDetails].[WhseKey], '"'),
	 [WhseID] = concat('"', [WarehouseDetails].[WhseID], '"'),
	 [WhseDescription] = concat('"', [WarehouseDetails].[WhseDescription], '"'),
	 [InvtGLAcctKey] = concat('"', [WarehouseDetails].[InvtGLAcctKey], '"'),
	 [Location] = concat('"', [WarehouseDetails].[Location], '"'),
	 [Region] = concat('"', [WarehouseDetails].[Region], '"'),
	 [RSM] = concat('"', [WarehouseDetails].[RSM], '"'),
	 [Territory] = concat('"', [WarehouseDetails].[Territory], '"'),
	 [EmailSMS] = concat('"', [WarehouseDetails].[EmailSMS], '"'),
	 [EmailMobile] = concat('"', [WarehouseDetails].[EmailMobile], '"'),
	 [GM] = concat('"', [WarehouseDetails].[GM], '"'),
	 [EmailGM] = concat('"', [WarehouseDetails].[EmailGM], '"'),
	 [EMailContracts] = concat('"', [WarehouseDetails].[EMailContracts], '"'),
	 [EmailRegionalMgr] = concat('"', [WarehouseDetails].[EmailRegionalMgr], '"'),
	 [RegionalMgr] = concat('"', [WarehouseDetails].[RegionalMgr], '"'),
	 [RSMPartnerID] = concat('"', [WarehouseDetails].[RSMPartnerID], '"'),
	 [RSMPartnerKey] = concat('"', [WarehouseDetails].[RSMPartnerKey], '"'),
	 [CreateDate] = convert(varchar(50), [WarehouseDetails].[CreateDate], 21),
	 [EmailDirMobile] = concat('"', [WarehouseDetails].[EmailDirMobile], '"')
from SinglePoint.dbo.WarehouseDetails