select
	 [DispatchID] = concat(char(34), [IncDispatch].[DispatchID], char(34)),
	 [IncidentID] = concat(char(34), [IncDispatch].[IncidentID], char(34)),
	 [ProblemSummary] = concat(char(34), [IncDispatch].[ProblemSummary], char(34)),
	 [SiteIdentifier] = concat(char(34), [IncDispatch].[SiteIdentifier], char(34)),
	 [FieldEngineerName] = concat(char(34), [IncDispatch].[FieldEngineerName], char(34)),
	 [ScheduledAppointment] = convert(varchar(50), [IncDispatch].[ScheduledAppointment], 21),
	 [SiteVisitDate] = convert(varchar(50), [IncDispatch].[SiteVisitDate], 21),
	 [NumberOfVisits] = concat(char(34), [IncDispatch].[NumberOfVisits], char(34)),
	 [ExtendedTimeReason] = concat(char(34), [IncDispatch].[ExtendedTimeReason], char(34)),
	 [WorkstreamID] = concat(char(34), [IncDispatch].[WorkstreamID], char(34)),
	 [WorkstreamSlaID] = concat(char(34), [IncDispatch].[WorkstreamSlaID], char(34)),
	 [isCustomerDefered] = concat(char(34), [IncDispatch].[isCustomerDefered], char(34)),
	 [isSlaWaived] = concat(char(34), [IncDispatch].[isSlaWaived], char(34)),
	 [isSlaMissed_SMS] = concat(char(34), [IncDispatch].[isSlaMissed_SMS], char(34)),
	 [isSlaMissed_Customer] = concat(char(34), [IncDispatch].[isSlaMissed_Customer], char(34)),
	 [isCancelled_Billable] = concat(char(34), [IncDispatch].[isCancelled_Billable], char(34)),
	 [isCancelled_NonBillable] = concat(char(34), [IncDispatch].[isCancelled_NonBillable], char(34)),
	 [CreateDate] = convert(varchar(50), [IncDispatch].[CreateDate], 21),
	 [CreateUserID] = concat(char(34), [IncDispatch].[CreateUserID], char(34)),
	 [LastUpdateDate] = convert(varchar(50), [IncDispatch].[LastUpdateDate], 21),
	 [LastUpdateUserID] = concat(char(34), [IncDispatch].[LastUpdateUserID], char(34)),
	 [StatusCodeID] = concat(char(34), [IncDispatch].[StatusCodeID], char(34)),
	 [ReScheduledAppointment] = convert(varchar(50), [IncDispatch].[ReScheduledAppointment], 21)
from SinglePoint.dbo.IncDispatch