select
	 [SiteAuditID] = concat(char(34), isNull(cast([SiteAudits].[SiteAuditID] as nvarchar(max)), '\N'), char(34)),
	 [CustomerID] = concat(char(34), isNull(cast([SiteAudits].[CustomerID] as nvarchar(max)), '\N'), char(34)),
	 [ContractHeaderID] = concat(char(34), isNull(cast([SiteAudits].[ContractHeaderID] as nvarchar(max)), '\N'), char(34)),
	 [StatusCodeID] = concat(char(34), isNull(cast([SiteAudits].[StatusCodeID] as nvarchar(max)), '\N'), char(34)),
	 [SROKey] = concat(char(34), isNull(cast([SiteAudits].[SROKey] as nvarchar(max)), '\N'), char(34)),
	 [SROID] = concat(char(34), isNull(cast([SiteAudits].[SROID] as nvarchar(max)), '\N'), char(34)),
	 [CreateByID] = concat(char(34), isNull(cast([SiteAudits].[CreateByID] as nvarchar(max)), '\N'), char(34)),
	 [CreateDate] = isNull(convert(varchar(50), [SiteAudits].[CreateDate], 21), '\N'),
	 [ChangedByID] = concat(char(34), isNull(cast([SiteAudits].[ChangedByID] as nvarchar(max)), '\N'), char(34)),
	 [LastChanged] = isNull(convert(varchar(50), [SiteAudits].[LastChanged], 21), '\N'),
	 [SROAddressID] = concat(char(34), isNull(cast([SiteAudits].[SROAddressID] as nvarchar(max)), '\N'), char(34)),
	 [CompleteDate] = isNull(convert(varchar(50), [SiteAudits].[CompleteDate], 21), '\N'),
	 [CompleteByID] = concat(char(34), isNull(cast([SiteAudits].[CompleteByID] as nvarchar(max)), '\N'), char(34)),
	 [OnSiteHours] = concat(char(34), isNull(cast([SiteAudits].[OnSiteHours] as nvarchar(max)), '\N'), char(34)),
	 [DataEntryHours] = concat(char(34), isNull(cast([SiteAudits].[DataEntryHours] as nvarchar(max)), '\N'), char(34)),
	 [SROWarehouseID] = concat(char(34), isNull(cast([SiteAudits].[SROWarehouseID] as nvarchar(max)), '\N'), char(34)),
	 [SROHeaderID] = concat(char(34), isNull(cast([SiteAudits].[SROHeaderID] as nvarchar(max)), '\N'), char(34)),
	 [SRONumber] = concat(char(34), isNull(cast([SiteAudits].[SRONumber] as nvarchar(max)), '\N'), char(34)),
	 [AssignedToID] = concat(char(34), isNull(cast([SiteAudits].[AssignedToID] as nvarchar(max)), '\N'), char(34)),
	 [ConfigImportFromMASDate] = isNull(convert(varchar(50), [SiteAudits].[ConfigImportFromMASDate], 21), '\N'),
	 [ConfigExportToMASDate] = isNull(convert(varchar(50), [SiteAudits].[ConfigExportToMASDate], 21), '\N')
from SinglePoint.dbo.SiteAudits