select
	 [PartyInvolvedID] = concat('"', [Customer_PartiesInvolved].[PartyInvolvedID], '"'),
	 [CustomerID] = concat('"', [Customer_PartiesInvolved].[CustomerID], '"'),
	 [Type] = concat('"', [Customer_PartiesInvolved].[Type], '"'),
	 [IsPrimary] = concat('"', [Customer_PartiesInvolved].[IsPrimary], '"'),
	 [Name] = concat('"', [Customer_PartiesInvolved].[Name], '"'),
	 [InvolvementStart] = convert(varchar(50), [Customer_PartiesInvolved].[InvolvementStart], 21),
	 [InvolvementEnd] = convert(varchar(50), [Customer_PartiesInvolved].[InvolvementEnd], 21),
	 [Status] = concat('"', [Customer_PartiesInvolved].[Status], '"'),
	 [ID] = concat('"', [Customer_PartiesInvolved].[ID], '"'),
	 [Phone_Primary] = concat('"', [Customer_PartiesInvolved].[Phone_Primary], '"'),
	 [Phone_Secondary] = concat('"', [Customer_PartiesInvolved].[Phone_Secondary], '"'),
	 [EMail] = concat('"', [Customer_PartiesInvolved].[EMail], '"'),
	 [EMailMobile] = concat('"', [Customer_PartiesInvolved].[EMailMobile], '"'),
	 [Address] = concat('"', [Customer_PartiesInvolved].[Address], '"'),
	 [CreateByID] = concat('"', [Customer_PartiesInvolved].[CreateByID], '"'),
	 [CreateDate] = convert(varchar(50), [Customer_PartiesInvolved].[CreateDate], 21),
	 [UpdateByID] = concat('"', [Customer_PartiesInvolved].[UpdateByID], '"'),
	 [UpdateDate] = convert(varchar(50), [Customer_PartiesInvolved].[UpdateDate], 21),
	 [Notes] = concat('"', [Customer_PartiesInvolved].[Notes], '"'),
	 [PartyTypeID] = concat('"', [Customer_PartiesInvolved].[PartyTypeID], '"')
from SinglePoint.dbo.Customer_PartiesInvolved