select
	 [RequisitionID] = concat('"', [PurchaseRequisition].[RequisitionID], '"'),
	 [RequisitionNumber] = concat('"', [PurchaseRequisition].[RequisitionNumber], '"'),
	 [ShipTo_Type] = concat('"', [PurchaseRequisition].[ShipTo_Type], '"'),
	 [ShipTo_WarehouseID] = concat('"', [PurchaseRequisition].[ShipTo_WarehouseID], '"'),
	 [ShipTo_AddressID] = concat('"', [PurchaseRequisition].[ShipTo_AddressID], '"'),
	 [CreatedBy_UserID] = concat('"', [PurchaseRequisition].[CreatedBy_UserID], '"'),
	 [CreatedDate] = convert(varchar(50), [PurchaseRequisition].[CreatedDate], 21),
	 [Status] = concat('"', [PurchaseRequisition].[Status], '"'),
	 [ObjectType] = concat('"', [PurchaseRequisition].[ObjectType], '"'),
	 [ObjectID] = concat('"', [PurchaseRequisition].[ObjectID], '"'),
	 [ObjectReference] = concat('"', [PurchaseRequisition].[ObjectReference], '"'),
	 [ServiceOrderID] = concat('"', [PurchaseRequisition].[ServiceOrderID], '"'),
	 [NeededByDateTime] = convert(varchar(50), [PurchaseRequisition].[NeededByDateTime], 21),
	 [Priority] = concat('"', [PurchaseRequisition].[Priority], '"'),
	 [ReasonCode] = concat('"', [PurchaseRequisition].[ReasonCode], '"'),
	 [SpecialNeeds] = concat('"', [PurchaseRequisition].[SpecialNeeds], '"'),
	 [ApprovalID] = concat('"', [PurchaseRequisition].[ApprovalID], '"'),
	 [ApproverID] = concat('"', [PurchaseRequisition].[ApproverID], '"'),
	 [LineNumber] = concat('"', [PurchaseRequisition].[LineNumber], '"'),
	 [RequisitionDescription] = concat('"', [PurchaseRequisition].[RequisitionDescription], '"'),
	 [RequisitionComments] = concat('"', [PurchaseRequisition].[RequisitionComments], '"'),
	 [SAP_SyncAck_DateTime] = convert(varchar(50), [PurchaseRequisition].[SAP_SyncAck_DateTime], 21),
	 [LastChanged] = convert(varchar(50), [PurchaseRequisition].[LastChanged], 21),
	 [ChangedByID] = concat('"', [PurchaseRequisition].[ChangedByID], '"'),
	 [UnitOfMeasure] = concat('"', [PurchaseRequisition].[UnitOfMeasure], '"')
from SinglePoint.dbo.PurchaseRequisition