select
	 [incReasonID] = concat(char(34), [incReasons].[incReasonID], char(34)),
	 [IncidentID] = concat(char(34), [incReasons].[IncidentID], char(34)),
	 [ReasonGenID] = concat(char(34), [incReasons].[ReasonGenID], char(34)),
	 [ReasonSpecID] = concat(char(34), [incReasons].[ReasonSpecID], char(34)),
	 [ResolutionGenID] = concat(char(34), [incReasons].[ResolutionGenID], char(34)),
	 [ResolutionSpecID] = concat(char(34), [incReasons].[ResolutionSpecID], char(34)),
	 [ReasonNotes] = concat(char(34), [incReasons].[ReasonNotes], char(34)),
	 [ResolutionNotes] = concat(char(34), [incReasons].[ResolutionNotes], char(34)),
	 [CreateByID] = concat(char(34), [incReasons].[CreateByID], char(34)),
	 [CreateDate] = convert(varchar(50), [incReasons].[CreateDate], 21),
	 [ChangedByID] = concat(char(34), [incReasons].[ChangedByID], char(34)),
	 [LastChanged] = convert(varchar(50), [incReasons].[LastChanged], 21),
	 [SSIncReasonKey] = concat(char(34), [incReasons].[SSIncReasonKey], char(34)),
	 [SPReasonInsert] = concat(char(34), [incReasons].[SPReasonInsert], char(34)),
	 [SPReasonUpdate] = concat(char(34), [incReasons].[SPReasonUpdate], char(34)),
	 [MobileReasonInsert] = concat(char(34), [incReasons].[MobileReasonInsert], char(34)),
	 [MobileReasonUpdate] = concat(char(34), [incReasons].[MobileReasonUpdate], char(34)),
	 [ImportFrom] = concat(char(34), [incReasons].[ImportFrom], char(34)),
	 [ImportDate] = convert(varchar(50), [incReasons].[ImportDate], 21),
	 [ImportBatch] = concat(char(34), [incReasons].[ImportBatch], char(34)),
	 [ReasonVerySpecID] = concat(char(34), [incReasons].[ReasonVerySpecID], char(34)),
	 [ResolutionVerySpecID] = concat(char(34), [incReasons].[ResolutionVerySpecID], char(34))
from SinglePoint.dbo.incReasons