select
	 [DispatchID] = concat('"', [IncDispatch].[DispatchID], '"'),
	 [IncidentID] = concat('"', [IncDispatch].[IncidentID], '"'),
	 [ProblemSummary] = concat('"', [IncDispatch].[ProblemSummary], '"'),
	 [SiteIdentifier] = concat('"', [IncDispatch].[SiteIdentifier], '"'),
	 [FieldEngineerName] = concat('"', [IncDispatch].[FieldEngineerName], '"'),
	 [ScheduledAppointment] = convert(varchar(50), [IncDispatch].[ScheduledAppointment], 21),
	 [SiteVisitDate] = convert(varchar(50), [IncDispatch].[SiteVisitDate], 21),
	 [NumberOfVisits] = concat('"', [IncDispatch].[NumberOfVisits], '"'),
	 [ExtendedTimeReason] = concat('"', [IncDispatch].[ExtendedTimeReason], '"'),
	 [WorkstreamID] = concat('"', [IncDispatch].[WorkstreamID], '"'),
	 [WorkstreamSlaID] = concat('"', [IncDispatch].[WorkstreamSlaID], '"'),
	 [isCustomerDefered] = concat('"', [IncDispatch].[isCustomerDefered], '"'),
	 [isSlaWaived] = concat('"', [IncDispatch].[isSlaWaived], '"'),
	 [isSlaMissed_SMS] = concat('"', [IncDispatch].[isSlaMissed_SMS], '"'),
	 [isSlaMissed_Customer] = concat('"', [IncDispatch].[isSlaMissed_Customer], '"'),
	 [isCancelled_Billable] = concat('"', [IncDispatch].[isCancelled_Billable], '"'),
	 [isCancelled_NonBillable] = concat('"', [IncDispatch].[isCancelled_NonBillable], '"'),
	 [CreateDate] = convert(varchar(50), [IncDispatch].[CreateDate], 21),
	 [CreateUserID] = concat('"', [IncDispatch].[CreateUserID], '"'),
	 [LastUpdateDate] = convert(varchar(50), [IncDispatch].[LastUpdateDate], 21),
	 [LastUpdateUserID] = concat('"', [IncDispatch].[LastUpdateUserID], '"'),
	 [StatusCodeID] = concat('"', [IncDispatch].[StatusCodeID], '"'),
	 [ReScheduledAppointment] = convert(varchar(50), [IncDispatch].[ReScheduledAppointment], 21)
from SinglePoint.dbo.IncDispatch