select
	 [SiteAuditID] = concat('"', [SiteAudits].[SiteAuditID], '"'),
	 [CustomerID] = concat('"', [SiteAudits].[CustomerID], '"'),
	 [ContractHeaderID] = concat('"', [SiteAudits].[ContractHeaderID], '"'),
	 [StatusCodeID] = concat('"', [SiteAudits].[StatusCodeID], '"'),
	 [SROKey] = concat('"', [SiteAudits].[SROKey], '"'),
	 [SROID] = concat('"', [SiteAudits].[SROID], '"'),
	 [CreateByID] = concat('"', [SiteAudits].[CreateByID], '"'),
	 [CreateDate] = convert(varchar(50), [SiteAudits].[CreateDate], 21),
	 [ChangedByID] = concat('"', [SiteAudits].[ChangedByID], '"'),
	 [LastChanged] = convert(varchar(50), [SiteAudits].[LastChanged], 21),
	 [SROAddressID] = concat('"', [SiteAudits].[SROAddressID], '"'),
	 [CompleteDate] = convert(varchar(50), [SiteAudits].[CompleteDate], 21),
	 [CompleteByID] = concat('"', [SiteAudits].[CompleteByID], '"'),
	 [OnSiteHours] = concat('"', [SiteAudits].[OnSiteHours], '"'),
	 [DataEntryHours] = concat('"', [SiteAudits].[DataEntryHours], '"'),
	 [SROWarehouseID] = concat('"', [SiteAudits].[SROWarehouseID], '"'),
	 [SROHeaderID] = concat('"', [SiteAudits].[SROHeaderID], '"'),
	 [SRONumber] = concat('"', [SiteAudits].[SRONumber], '"'),
	 [AssignedToID] = concat('"', [SiteAudits].[AssignedToID], '"'),
	 [ConfigImportFromMASDate] = convert(varchar(50), [SiteAudits].[ConfigImportFromMASDate], 21),
	 [ConfigExportToMASDate] = convert(varchar(50), [SiteAudits].[ConfigExportToMASDate], 21)
from SinglePoint.dbo.SiteAudits