select
	 [IncidentID] = concat('"', [IncServiceOrders].[IncidentID], '"'),
	 [ServiceOrderID] = concat('"', [IncServiceOrders].[ServiceOrderID], '"'),
	 [ServiceOrder_SAP_Key] = concat('"', [IncServiceOrders].[ServiceOrder_SAP_Key], '"'),
	 [Type] = concat('"', [IncServiceOrders].[Type], '"'),
	 [RequestDateTime] = convert(varchar(50), [IncServiceOrders].[RequestDateTime], 21),
	 [AcknowledgedDateTime] = convert(varchar(50), [IncServiceOrders].[AcknowledgedDateTime], 21),
	 [SAP_Plant_Key] = concat('"', [IncServiceOrders].[SAP_Plant_Key], '"'),
	 [SAP_Sold_To_Key] = concat('"', [IncServiceOrders].[SAP_Sold_To_Key], '"'),
	 [SAP_Ship_To_Key] = concat('"', [IncServiceOrders].[SAP_Ship_To_Key], '"'),
	 [SAP_Contract_Key] = concat('"', [IncServiceOrders].[SAP_Contract_Key], '"'),
	 [SAP_Contract_Line] = concat('"', [IncServiceOrders].[SAP_Contract_Line], '"'),
	 [SAP_Service_Material_Key] = concat('"', [IncServiceOrders].[SAP_Service_Material_Key], '"'),
	 [SAP_Equipment_Key] = concat('"', [IncServiceOrders].[SAP_Equipment_Key], '"'),
	 [Serial_Number] = concat('"', [IncServiceOrders].[Serial_Number], '"'),
	 [Sales_Organization] = concat('"', [IncServiceOrders].[Sales_Organization], '"'),
	 [Distribution_Channel] = concat('"', [IncServiceOrders].[Distribution_Channel], '"'),
	 [Division] = concat('"', [IncServiceOrders].[Division], '"'),
	 [CreateByID] = concat('"', [IncServiceOrders].[CreateByID], '"'),
	 [CreateDate] = convert(varchar(50), [IncServiceOrders].[CreateDate], 21),
	 [Status] = concat('"', [IncServiceOrders].[Status], '"'),
	 [StatusMessage] = concat('"', [IncServiceOrders].[StatusMessage], '"'),
	 [ProblemDescription] = concat('"', [IncServiceOrders].[ProblemDescription], '"'),
	 [Requester] = concat('"', [IncServiceOrders].[Requester], '"'),
	 [PointOfContact] = concat('"', [IncServiceOrders].[PointOfContact], '"'),
	 [BatchID] = concat('"', [IncServiceOrders].[BatchID], '"'),
	 [BillToCustomerID] = concat('"', [IncServiceOrders].[BillToCustomerID], '"')
from SinglePoint.dbo.IncServiceOrders