select
	 [IncidentID] = concat(char(34), [IncServiceOrders].[IncidentID], char(34)),
	 [ServiceOrderID] = concat(char(34), [IncServiceOrders].[ServiceOrderID], char(34)),
	 [ServiceOrder_SAP_Key] = concat(char(34), [IncServiceOrders].[ServiceOrder_SAP_Key], char(34)),
	 [Type] = concat(char(34), [IncServiceOrders].[Type], char(34)),
	 [RequestDateTime] = convert(varchar(50), [IncServiceOrders].[RequestDateTime], 21),
	 [AcknowledgedDateTime] = convert(varchar(50), [IncServiceOrders].[AcknowledgedDateTime], 21),
	 [SAP_Plant_Key] = concat(char(34), [IncServiceOrders].[SAP_Plant_Key], char(34)),
	 [SAP_Sold_To_Key] = concat(char(34), [IncServiceOrders].[SAP_Sold_To_Key], char(34)),
	 [SAP_Ship_To_Key] = concat(char(34), [IncServiceOrders].[SAP_Ship_To_Key], char(34)),
	 [SAP_Contract_Key] = concat(char(34), [IncServiceOrders].[SAP_Contract_Key], char(34)),
	 [SAP_Contract_Line] = concat(char(34), [IncServiceOrders].[SAP_Contract_Line], char(34)),
	 [SAP_Service_Material_Key] = concat(char(34), [IncServiceOrders].[SAP_Service_Material_Key], char(34)),
	 [SAP_Equipment_Key] = concat(char(34), [IncServiceOrders].[SAP_Equipment_Key], char(34)),
	 [Serial_Number] = concat(char(34), [IncServiceOrders].[Serial_Number], char(34)),
	 [Sales_Organization] = concat(char(34), [IncServiceOrders].[Sales_Organization], char(34)),
	 [Distribution_Channel] = concat(char(34), [IncServiceOrders].[Distribution_Channel], char(34)),
	 [Division] = concat(char(34), [IncServiceOrders].[Division], char(34)),
	 [CreateByID] = concat(char(34), [IncServiceOrders].[CreateByID], char(34)),
	 [CreateDate] = convert(varchar(50), [IncServiceOrders].[CreateDate], 21),
	 [Status] = concat(char(34), [IncServiceOrders].[Status], char(34)),
	 [StatusMessage] = concat(char(34), [IncServiceOrders].[StatusMessage], char(34)),
	 [ProblemDescription] = concat(char(34), [IncServiceOrders].[ProblemDescription], char(34)),
	 [Requester] = concat(char(34), [IncServiceOrders].[Requester], char(34)),
	 [PointOfContact] = concat(char(34), [IncServiceOrders].[PointOfContact], char(34)),
	 [BatchID] = concat(char(34), [IncServiceOrders].[BatchID], char(34)),
	 [BillToCustomerID] = concat(char(34), [IncServiceOrders].[BillToCustomerID], char(34))
from SinglePoint.dbo.IncServiceOrders