select
	 [PartyInvolvedID] = quotename([PartiesInvolved].[PartyInvolvedID], char(34)),
	 [FKID] = quotename([PartiesInvolved].[FKID], char(34)),
	 [Type] = quotename([PartiesInvolved].[Type], char(34)),
	 [IsPrimary] = quotename([PartiesInvolved].[IsPrimary], char(34)),
	 [Name] = quotename([PartiesInvolved].[Name], char(34)),
	 [InvolvementStart] = convert(varchar(50), [PartiesInvolved].[InvolvementStart], 21),
	 [InvolvementEnd] = convert(varchar(50), [PartiesInvolved].[InvolvementEnd], 21),
	 [Status] = quotename([PartiesInvolved].[Status], char(34)),
	 [ID] = quotename([PartiesInvolved].[ID], char(34)),
	 [PhonePrimary] = quotename([PartiesInvolved].[PhonePrimary], char(34)),
	 [PhoneSecondary] = quotename([PartiesInvolved].[PhoneSecondary], char(34)),
	 [EMail] = quotename([PartiesInvolved].[EMail], char(34)),
	 [EMailMobile] = quotename([PartiesInvolved].[EMailMobile], char(34)),
	 [Address] = quotename([PartiesInvolved].[Address], char(34)),
	 [CreateByID] = quotename([PartiesInvolved].[CreateByID], char(34)),
	 [CreateDate] = convert(varchar(50), [PartiesInvolved].[CreateDate], 21),
	 [UpdateByID] = quotename([PartiesInvolved].[UpdateByID], char(34)),
	 [UpdateDate] = convert(varchar(50), [PartiesInvolved].[UpdateDate], 21),
	 [Notes] = quotename([PartiesInvolved].[Notes], char(34)),
	 [IsNotificationRecipient] = quotename([PartiesInvolved].[IsNotificationRecipient], char(34)),
	 [UserID] = quotename([PartiesInvolved].[UserID], char(34)),
	 [PartyTypeID] = quotename([PartiesInvolved].[PartyTypeID], char(34))
from SinglePoint.dbo.PartiesInvolved