select
	 [RequisitionID] = concat(char(34), isNull(cast([PurchaseRequisition].[RequisitionID] as nvarchar(max)), '\N'), char(34)),
	 [RequisitionNumber] = concat(char(34), isNull(cast([PurchaseRequisition].[RequisitionNumber] as nvarchar(max)), '\N'), char(34)),
	 [ShipTo_Type] = concat(char(34), isNull(cast([PurchaseRequisition].[ShipTo_Type] as nvarchar(max)), '\N'), char(34)),
	 [ShipTo_WarehouseID] = concat(char(34), isNull(cast([PurchaseRequisition].[ShipTo_WarehouseID] as nvarchar(max)), '\N'), char(34)),
	 [ShipTo_AddressID] = concat(char(34), isNull(cast([PurchaseRequisition].[ShipTo_AddressID] as nvarchar(max)), '\N'), char(34)),
	 [CreatedBy_UserID] = concat(char(34), isNull(cast([PurchaseRequisition].[CreatedBy_UserID] as nvarchar(max)), '\N'), char(34)),
	 [CreatedDate] = isNull(convert(varchar(50), [PurchaseRequisition].[CreatedDate], 21), '\N'),
	 [Status] = concat(char(34), isNull(cast([PurchaseRequisition].[Status] as nvarchar(max)), '\N'), char(34)),
	 [ObjectType] = concat(char(34), isNull(cast([PurchaseRequisition].[ObjectType] as nvarchar(max)), '\N'), char(34)),
	 [ObjectID] = concat(char(34), isNull(cast([PurchaseRequisition].[ObjectID] as nvarchar(max)), '\N'), char(34)),
	 [ObjectReference] = concat(char(34), isNull(cast([PurchaseRequisition].[ObjectReference] as nvarchar(max)), '\N'), char(34)),
	 [ServiceOrderID] = concat(char(34), isNull(cast([PurchaseRequisition].[ServiceOrderID] as nvarchar(max)), '\N'), char(34)),
	 [NeededByDateTime] = isNull(convert(varchar(50), [PurchaseRequisition].[NeededByDateTime], 21), '\N'),
	 [Priority] = concat(char(34), isNull(cast([PurchaseRequisition].[Priority] as nvarchar(max)), '\N'), char(34)),
	 [ReasonCode] = concat(char(34), isNull(cast([PurchaseRequisition].[ReasonCode] as nvarchar(max)), '\N'), char(34)),
	 [SpecialNeeds] = concat(char(34), isNull(cast([PurchaseRequisition].[SpecialNeeds] as nvarchar(max)), '\N'), char(34)),
	 [ApprovalID] = concat(char(34), isNull(cast([PurchaseRequisition].[ApprovalID] as nvarchar(max)), '\N'), char(34)),
	 [ApproverID] = concat(char(34), isNull(cast([PurchaseRequisition].[ApproverID] as nvarchar(max)), '\N'), char(34)),
	 [LineNumber] = concat(char(34), isNull(cast([PurchaseRequisition].[LineNumber] as nvarchar(max)), '\N'), char(34)),
	 [RequisitionDescription] = concat(char(34), isNull(cast([PurchaseRequisition].[RequisitionDescription] as nvarchar(max)), '\N'), char(34)),
	 [RequisitionComments] = concat(char(34), isNull(cast([PurchaseRequisition].[RequisitionComments] as nvarchar(max)), '\N'), char(34)),
	 [SAP_SyncAck_DateTime] = isNull(convert(varchar(50), [PurchaseRequisition].[SAP_SyncAck_DateTime], 21), '\N'),
	 [LastChanged] = isNull(convert(varchar(50), [PurchaseRequisition].[LastChanged], 21), '\N'),
	 [ChangedByID] = concat(char(34), isNull(cast([PurchaseRequisition].[ChangedByID] as nvarchar(max)), '\N'), char(34)),
	 [UnitOfMeasure] = concat(char(34), isNull(cast([PurchaseRequisition].[UnitOfMeasure] as nvarchar(max)), '\N'), char(34))
from SinglePoint.dbo.PurchaseRequisition