select
	 [AddressID] = concat(char(34), [AddressDetails].[AddressID], char(34)),
	 [WarehouseID] = concat(char(34), [AddressDetails].[WarehouseID], char(34)),
	 [SalesTerritoryID] = concat(char(34), [AddressDetails].[SalesTerritoryID], char(34)),
	 [TaxScheduleID] = concat(char(34), [AddressDetails].[TaxScheduleID], char(34)),
	 [DefaultContactID] = concat(char(34), [AddressDetails].[DefaultContactID], char(34)),
	 [ChangedByID] = concat(char(34), [AddressDetails].[ChangedByID], char(34)),
	 [SalesPersonID] = concat(char(34), [AddressDetails].[SalesPersonID], char(34)),
	 [LastChanged] = convert(varchar(50), [AddressDetails].[LastChanged], 21),
	 [DrivingDistance_Miles] = concat(char(34), [AddressDetails].[DrivingDistance_Miles], char(34)),
	 [DrivingTime_Minutes] = concat(char(34), [AddressDetails].[DrivingTime_Minutes], char(34)),
	 [Driving_UpdateRequired] = concat(char(34), [AddressDetails].[Driving_UpdateRequired], char(34)),
	 [AsyncStatus] = concat(char(34), [AddressDetails].[AsyncStatus], char(34)),
	 [AsyncError] = concat(char(34), [AddressDetails].[AsyncError], char(34)),
	 [CreateDate] = convert(varchar(50), [AddressDetails].[CreateDate], 21),
	 [ServiceWarehouseID] = concat(char(34), [AddressDetails].[ServiceWarehouseID], char(34)),
	 [TaxClass] = concat(char(34), [AddressDetails].[TaxClass], char(34)),
	 [GenericAddressFlag] = concat(char(34), [AddressDetails].[GenericAddressFlag], char(34)),
	 [GenericContactFlag] = concat(char(34), [AddressDetails].[GenericContactFlag], char(34)),
	 [WarehouseCalculation_Method] = concat(char(34), [AddressDetails].[WarehouseCalculation_Method], char(34)),
	 [WarehouseCalculation_Date] = convert(varchar(50), [AddressDetails].[WarehouseCalculation_Date], 21)
from SinglePoint.dbo.AddressDetails