select
	 [ForwardStockingLocationID] = concat('"', [Warehouse_FSL].[ForwardStockingLocationID], '"'),
	 [Name] = concat('"', [Warehouse_FSL].[Name], '"'),
	 [Description] = concat('"', [Warehouse_FSL].[Description], '"'),
	 [AddressID] = concat('"', [Warehouse_FSL].[AddressID], '"'),
	 [Status] = concat('"', [Warehouse_FSL].[Status], '"'),
	 [MonthlyCost] = concat('"', [Warehouse_FSL].[MonthlyCost], '"'),
	 [CreatedDate] = convert(varchar(50), [Warehouse_FSL].[CreatedDate], 21),
	 [CreatedByUserID] = concat('"', [Warehouse_FSL].[CreatedByUserID], '"'),
	 [LastUpdatedDate] = convert(varchar(50), [Warehouse_FSL].[LastUpdatedDate], 21),
	 [LastUpdatedByUserID] = concat('"', [Warehouse_FSL].[LastUpdatedByUserID], '"'),
	 [Oracle_InventoryOrg_ID] = concat('"', [Warehouse_FSL].[Oracle_InventoryOrg_ID], '"'),
	 [Oracle_InventoryOrg_Code] = concat('"', [Warehouse_FSL].[Oracle_InventoryOrg_Code], '"'),
	 [Oracle_InventoryOrg_Name] = concat('"', [Warehouse_FSL].[Oracle_InventoryOrg_Name], '"'),
	 [ForwardStockingLocationKey] = concat('"', [Warehouse_FSL].[ForwardStockingLocationKey], '"'),
	 [VendorName] = concat('"', [Warehouse_FSL].[VendorName], '"'),
	 [VendorLocation_ID] = concat('"', [Warehouse_FSL].[VendorLocation_ID], '"'),
	 [Radius] = concat('"', [Warehouse_FSL].[Radius], '"'),
	 [Type] = concat('"', [Warehouse_FSL].[Type], '"')
from SinglePoint.dbo.Warehouse_FSL