select
	 [UnitGuid] = concat(char(34), isNull(replace(cast([tqoUnit].[UnitGuid] as nvarchar(max)), char(34), char(0)), '\N'), char(34)),
	 [CustomerID] = concat(char(34), isNull(replace(cast([tqoUnit].[CustomerID] as nvarchar(max)), char(34), char(0)), '\N'), char(34)),
	 [BOMGuid] = concat(char(34), isNull(replace(cast([tqoUnit].[BOMGuid] as nvarchar(max)), char(34), char(0)), '\N'), char(34)),
	 [BillToCustAddrGuid] = concat(char(34), isNull(replace(cast([tqoUnit].[BillToCustAddrGuid] as nvarchar(max)), char(34), char(0)), '\N'), char(34)),
	 [ShipToCustAddrGuid] = concat(char(34), isNull(replace(cast([tqoUnit].[ShipToCustAddrGuid] as nvarchar(max)), char(34), char(0)), '\N'), char(34)),
	 [MASSrvDealer] = concat(char(34), isNull(replace(cast([tqoUnit].[MASSrvDealer] as nvarchar(max)), char(34), char(0)), '\N'), char(34)),
	 [MASUnitStatKey] = concat(char(34), isNull(replace(cast([tqoUnit].[MASUnitStatKey] as nvarchar(max)), char(34), char(0)), '\N'), char(34)),
	 [HwPO_UserFld1] = concat(char(34), isNull(replace(cast([tqoUnit].[HwPO_UserFld1] as nvarchar(max)), char(34), char(0)), '\N'), char(34)),
	 [HwPOLine_UserFld2] = concat(char(34), isNull(replace(cast([tqoUnit].[HwPOLine_UserFld2] as nvarchar(max)), char(34), char(0)), '\N'), char(34)),
	 [SwSupportVendors_UserFld3] = concat(char(34), isNull(replace(cast([tqoUnit].[SwSupportVendors_UserFld3] as nvarchar(max)), char(34), char(0)), '\N'), char(34)),
	 [SwPO_UserFld4] = concat(char(34), isNull(replace(cast([tqoUnit].[SwPO_UserFld4] as nvarchar(max)), char(34), char(0)), '\N'), char(34)),
	 [SwPOLine_UserFld5] = concat(char(34), isNull(replace(cast([tqoUnit].[SwPOLine_UserFld5] as nvarchar(max)), char(34), char(0)), '\N'), char(34)),
	 [ChangedByID] = concat(char(34), isNull(replace(cast([tqoUnit].[ChangedByID] as nvarchar(max)), char(34), char(0)), '\N'), char(34)),
	 [LastChanged] = isNull(convert(varchar(50), [tqoUnit].[LastChanged], 21), '\N'),
	 [CreateByID] = concat(char(34), isNull(replace(cast([tqoUnit].[CreateByID] as nvarchar(max)), char(34), char(0)), '\N'), char(34)),
	 [CreateDate] = isNull(convert(varchar(50), [tqoUnit].[CreateDate], 21), '\N'),
	 [TopSerialNum] = concat(char(34), isNull(replace(cast([tqoUnit].[TopSerialNum] as nvarchar(max)), char(34), char(0)), '\N'), char(34)),
	 [TopShortDesc] = concat(char(34), isNull(replace(cast([tqoUnit].[TopShortDesc] as nvarchar(max)), char(34), char(0)), '\N'), char(34)),
	 [NodeName] = concat(char(34), isNull(replace(cast([tqoUnit].[NodeName] as nvarchar(max)), char(34), char(0)), '\N'), char(34)),
	 [PrevUnitGuid] = concat(char(34), isNull(replace(cast([tqoUnit].[PrevUnitGuid] as nvarchar(max)), char(34), char(0)), '\N'), char(34)),
	 [MASUnitKey] = concat(char(34), isNull(replace(cast([tqoUnit].[MASUnitKey] as nvarchar(max)), char(34), char(0)), '\N'), char(34)),
	 [WebModelCodeID] = concat(char(34), isNull(replace(cast([tqoUnit].[WebModelCodeID] as nvarchar(max)), char(34), char(0)), '\N'), char(34)),
	 [WebModelCode] = concat(char(34), isNull(replace(cast([tqoUnit].[WebModelCode] as nvarchar(max)), char(34), char(0)), '\N'), char(34)),
	 [FromAssetHeaderID] = concat(char(34), isNull(replace(cast([tqoUnit].[FromAssetHeaderID] as nvarchar(max)), char(34), char(0)), '\N'), char(34)),
	 [RecSource] = concat(char(34), isNull(replace(cast([tqoUnit].[RecSource] as nvarchar(max)), char(34), char(0)), '\N'), char(34))
from SinglePoint.dbo.tqoUnit with(nolock)