select
	 [PartyInvolvedID] = isNull(quotename([PartyInvolvedID], char(34)), '\N'),
	 [FKID] = isNull(quotename([FKID], char(34)), '\N'),
	 [Type] = isNull(quotename([Type], char(34)), '\N'),
	 [IsPrimary] = isNull(quotename([IsPrimary], char(34)), '\N'),
	 [Name] = isNull(quotename([Name], char(34)), '\N'),
	 [InvolvementStart] = isNull(convert(varchar(50), [InvolvementStart], 21), '\N'),
	 [InvolvementEnd] = isNull(convert(varchar(50), [InvolvementEnd], 21), '\N'),
	 [Status] = isNull(quotename([Status], char(34)), '\N'),
	 [ID] = isNull(quotename([ID], char(34)), '\N'),
	 [PhonePrimary] = isNull(quotename([PhonePrimary], char(34)), '\N'),
	 [PhoneSecondary] = isNull(quotename([PhoneSecondary], char(34)), '\N'),
	 [EMail] = isNull(quotename([EMail], char(34)), '\N'),
	 [EMailMobile] = isNull(quotename([EMailMobile], char(34)), '\N'),
	 [Address] = isNull(quotename([Address], char(34)), '\N'),
	 [CreateByID] = isNull(quotename([CreateByID], char(34)), '\N'),
	 [CreateDate] = isNull(convert(varchar(50), [CreateDate], 21), '\N'),
	 [UpdateByID] = isNull(quotename([UpdateByID], char(34)), '\N'),
	 [UpdateDate] = isNull(convert(varchar(50), [UpdateDate], 21), '\N'),
	 [Notes] = isNull(quotename([Notes], char(34)), '\N'),
	 [IsNotificationRecipient] = isNull(quotename([IsNotificationRecipient], char(34)), '\N'),
	 [UserID] = isNull(quotename([UserID], char(34)), '\N'),
	 [PartyTypeID] = isNull(quotename([PartyTypeID], char(34)), '\N')
from SinglePoint.dbo.PartiesInvolved