select
	 [PartyInvolvedID] = concat(char(34), isNull(replace(cast([Customer_PartiesInvolved].[PartyInvolvedID] as nvarchar(max)), char(34), char(0)), '\N'), char(34)),
	 [CustomerID] = concat(char(34), isNull(replace(cast([Customer_PartiesInvolved].[CustomerID] as nvarchar(max)), char(34), char(0)), '\N'), char(34)),
	 [Type] = concat(char(34), isNull(replace(cast([Customer_PartiesInvolved].[Type] as nvarchar(max)), char(34), char(0)), '\N'), char(34)),
	 [IsPrimary] = concat(char(34), isNull(replace(cast([Customer_PartiesInvolved].[IsPrimary] as nvarchar(max)), char(34), char(0)), '\N'), char(34)),
	 [Name] = concat(char(34), isNull(replace(cast([Customer_PartiesInvolved].[Name] as nvarchar(max)), char(34), char(0)), '\N'), char(34)),
	 [InvolvementStart] = isNull(convert(varchar(50), [Customer_PartiesInvolved].[InvolvementStart], 21), '\N'),
	 [InvolvementEnd] = isNull(convert(varchar(50), [Customer_PartiesInvolved].[InvolvementEnd], 21), '\N'),
	 [Status] = concat(char(34), isNull(replace(cast([Customer_PartiesInvolved].[Status] as nvarchar(max)), char(34), char(0)), '\N'), char(34)),
	 [ID] = concat(char(34), isNull(replace(cast([Customer_PartiesInvolved].[ID] as nvarchar(max)), char(34), char(0)), '\N'), char(34)),
	 [Phone_Primary] = concat(char(34), isNull(replace(cast([Customer_PartiesInvolved].[Phone_Primary] as nvarchar(max)), char(34), char(0)), '\N'), char(34)),
	 [Phone_Secondary] = concat(char(34), isNull(replace(cast([Customer_PartiesInvolved].[Phone_Secondary] as nvarchar(max)), char(34), char(0)), '\N'), char(34)),
	 [EMail] = concat(char(34), isNull(replace(cast([Customer_PartiesInvolved].[EMail] as nvarchar(max)), char(34), char(0)), '\N'), char(34)),
	 [EMailMobile] = concat(char(34), isNull(replace(cast([Customer_PartiesInvolved].[EMailMobile] as nvarchar(max)), char(34), char(0)), '\N'), char(34)),
	 [Address] = concat(char(34), isNull(replace(cast([Customer_PartiesInvolved].[Address] as nvarchar(max)), char(34), char(0)), '\N'), char(34)),
	 [CreateByID] = concat(char(34), isNull(replace(cast([Customer_PartiesInvolved].[CreateByID] as nvarchar(max)), char(34), char(0)), '\N'), char(34)),
	 [CreateDate] = isNull(convert(varchar(50), [Customer_PartiesInvolved].[CreateDate], 21), '\N'),
	 [UpdateByID] = concat(char(34), isNull(replace(cast([Customer_PartiesInvolved].[UpdateByID] as nvarchar(max)), char(34), char(0)), '\N'), char(34)),
	 [UpdateDate] = isNull(convert(varchar(50), [Customer_PartiesInvolved].[UpdateDate], 21), '\N'),
	 [Notes] = concat(char(34), isNull(replace(cast([Customer_PartiesInvolved].[Notes] as nvarchar(max)), char(34), char(0)), '\N'), char(34)),
	 [PartyTypeID] = concat(char(34), isNull(replace(cast([Customer_PartiesInvolved].[PartyTypeID] as nvarchar(max)), char(34), char(0)), '\N'), char(34))
from SinglePoint.dbo.Customer_PartiesInvolved