select
	 [IncidentSlaID] = isNull(cast([Incident_SLA].[IncidentSlaID] as varchar(36)), '\N'),
	 [IncidentID] = isNull(cast([Incident_SLA].[IncidentID] as varchar(36)), '\N'),
	 [SlaTermID] = isNull(cast([Incident_SLA].[SlaTermID] as varchar(36)), '\N'),
	 [SlaCallProfileID] = isNull(cast([Incident_SLA].[SlaCallProfileID] as varchar(36)), '\N'),
	 [SlaServiceProfileID] = isNull(cast([Incident_SLA].[SlaServiceProfileID] as varchar(36)), '\N'),
	 [SlaStartTime] = isNull(convert(varchar(50), [Incident_SLA].[SlaStartTime], 21), '\N'),
	 [SlaDeadline] = isNull(convert(varchar(50), [Incident_SLA].[SlaDeadline], 21), '\N'),
	 [SlaStatus] = concat(char(34), isNull(replace(cast([Incident_SLA].[SlaStatus] as nvarchar(50)), char(34), char(0)), '\N'), char(34)),
	 [SlaTotalTimeDurationAllowed_Minutes] = isNull(cast([Incident_SLA].[SlaTotalTimeDurationAllowed_Minutes] as varchar(36)), '\N'),
	 [SlaTimeDurationForClosedActivities_Minutes] = isNull(cast([Incident_SLA].[SlaTimeDurationForClosedActivities_Minutes] as varchar(36)), '\N'),
	 [SlaDisposition] = concat(char(34), isNull(replace(cast([Incident_SLA].[SlaDisposition] as nvarchar(50)), char(34), char(0)), '\N'), char(34)),
	 [SlaDispositionDeterminationDateTime] = isNull(convert(varchar(50), [Incident_SLA].[SlaDispositionDeterminationDateTime], 21), '\N'),
	 [SlaRequiredTravelStartTime] = isNull(convert(varchar(50), [Incident_SLA].[SlaRequiredTravelStartTime], 21), '\N'),
	 [SlaJeopordyStartTime] = isNull(convert(varchar(50), [Incident_SLA].[SlaJeopordyStartTime], 21), '\N'),
	 [SlaServiceCommitment] = concat(char(34), isNull(replace(cast([Incident_SLA].[SlaServiceCommitment] as nvarchar(50)), char(34), char(0)), '\N'), char(34)),
	 [SlaAcceptanceDateTime] = isNull(convert(varchar(50), [Incident_SLA].[SlaAcceptanceDateTime], 21), '\N'),
	 [SlaTimeZoneKey] = isNull(cast([Incident_SLA].[SlaTimeZoneKey] as varchar(36)), '\N'),
	 [SlaDisposition_Actual] = concat(char(34), isNull(replace(cast([Incident_SLA].[SlaDisposition_Actual] as nvarchar(50)), char(34), char(0)), '\N'), char(34))
from Ticketing.dbo.Incident_SLA