select
	 [TransactionID] = concat(char(34), isNull(cast([Incident_ServiceOrder_Parts_Reservations].[TransactionID] as nvarchar(max)), '\N'), char(34)),
	 [RequestID] = concat(char(34), isNull(cast([Incident_ServiceOrder_Parts_Reservations].[RequestID] as nvarchar(max)), '\N'), char(34)),
	 [ItemID] = concat(char(34), isNull(cast([Incident_ServiceOrder_Parts_Reservations].[ItemID] as nvarchar(max)), '\N'), char(34)),
	 [ItemNumber] = concat(char(34), isNull(cast([Incident_ServiceOrder_Parts_Reservations].[ItemNumber] as nvarchar(max)), '\N'), char(34)),
	 [SerialNumber] = concat(char(34), isNull(cast([Incident_ServiceOrder_Parts_Reservations].[SerialNumber] as nvarchar(max)), '\N'), char(34)),
	 [Quantity] = concat(char(34), isNull(cast([Incident_ServiceOrder_Parts_Reservations].[Quantity] as nvarchar(max)), '\N'), char(34)),
	 [WarehouseID] = concat(char(34), isNull(cast([Incident_ServiceOrder_Parts_Reservations].[WarehouseID] as nvarchar(max)), '\N'), char(34)),
	 [StorageLocation] = concat(char(34), isNull(cast([Incident_ServiceOrder_Parts_Reservations].[StorageLocation] as nvarchar(max)), '\N'), char(34)),
	 [Status] = concat(char(34), isNull(cast([Incident_ServiceOrder_Parts_Reservations].[Status] as nvarchar(max)), '\N'), char(34)),
	 [CreateByUserID] = concat(char(34), isNull(cast([Incident_ServiceOrder_Parts_Reservations].[CreateByUserID] as nvarchar(max)), '\N'), char(34)),
	 [CreatedDate] = isNull(convert(varchar(50), [Incident_ServiceOrder_Parts_Reservations].[CreatedDate], 21), '\N'),
	 [UpdateByUserID] = concat(char(34), isNull(cast([Incident_ServiceOrder_Parts_Reservations].[UpdateByUserID] as nvarchar(max)), '\N'), char(34)),
	 [UpdateDate] = isNull(convert(varchar(50), [Incident_ServiceOrder_Parts_Reservations].[UpdateDate], 21), '\N'),
	 [ERPMessage] = concat(char(34), isNull(cast([Incident_ServiceOrder_Parts_Reservations].[ERPMessage] as nvarchar(max)), '\N'), char(34)),
	 [ERPStatus] = concat(char(34), isNull(cast([Incident_ServiceOrder_Parts_Reservations].[ERPStatus] as nvarchar(max)), '\N'), char(34)),
	 [ERPAckDate] = isNull(convert(varchar(50), [Incident_ServiceOrder_Parts_Reservations].[ERPAckDate], 21), '\N'),
	 [Batch] = concat(char(34), isNull(cast([Incident_ServiceOrder_Parts_Reservations].[Batch] as nvarchar(max)), '\N'), char(34)),
	 [StorageLocationDescription] = concat(char(34), isNull(cast([Incident_ServiceOrder_Parts_Reservations].[StorageLocationDescription] as nvarchar(max)), '\N'), char(34)),
	 [ReturnStorageLocation] = concat(char(34), isNull(cast([Incident_ServiceOrder_Parts_Reservations].[ReturnStorageLocation] as nvarchar(max)), '\N'), char(34)),
	 [ReturnStorageLocationDescription] = concat(char(34), isNull(cast([Incident_ServiceOrder_Parts_Reservations].[ReturnStorageLocationDescription] as nvarchar(max)), '\N'), char(34)),
	 [ReservationDateTIme] = isNull(convert(varchar(50), [Incident_ServiceOrder_Parts_Reservations].[ReservationDateTIme], 21), '\N'),
	 [FieldReportCompleteDateTime] = isNull(convert(varchar(50), [Incident_ServiceOrder_Parts_Reservations].[FieldReportCompleteDateTime], 21), '\N')
from Ticketing.dbo.Incident_ServiceOrder_Parts_Reservations