select
	 [TransactionID] = concat(char(34), [Incident_ServiceOrder_Parts_Reservations].[TransactionID], char(34)),
	 [RequestID] = concat(char(34), [Incident_ServiceOrder_Parts_Reservations].[RequestID], char(34)),
	 [ItemID] = concat(char(34), [Incident_ServiceOrder_Parts_Reservations].[ItemID], char(34)),
	 [ItemNumber] = concat(char(34), [Incident_ServiceOrder_Parts_Reservations].[ItemNumber], char(34)),
	 [SerialNumber] = concat(char(34), [Incident_ServiceOrder_Parts_Reservations].[SerialNumber], char(34)),
	 [Quantity] = concat(char(34), [Incident_ServiceOrder_Parts_Reservations].[Quantity], char(34)),
	 [WarehouseID] = concat(char(34), [Incident_ServiceOrder_Parts_Reservations].[WarehouseID], char(34)),
	 [StorageLocation] = concat(char(34), [Incident_ServiceOrder_Parts_Reservations].[StorageLocation], char(34)),
	 [Status] = concat(char(34), [Incident_ServiceOrder_Parts_Reservations].[Status], char(34)),
	 [CreateByUserID] = concat(char(34), [Incident_ServiceOrder_Parts_Reservations].[CreateByUserID], char(34)),
	 [CreatedDate] = convert(varchar(50), [Incident_ServiceOrder_Parts_Reservations].[CreatedDate], 21),
	 [UpdateByUserID] = concat(char(34), [Incident_ServiceOrder_Parts_Reservations].[UpdateByUserID], char(34)),
	 [UpdateDate] = convert(varchar(50), [Incident_ServiceOrder_Parts_Reservations].[UpdateDate], 21),
	 [ERPMessage] = concat(char(34), [Incident_ServiceOrder_Parts_Reservations].[ERPMessage], char(34)),
	 [ERPStatus] = concat(char(34), [Incident_ServiceOrder_Parts_Reservations].[ERPStatus], char(34)),
	 [ERPAckDate] = convert(varchar(50), [Incident_ServiceOrder_Parts_Reservations].[ERPAckDate], 21),
	 [Batch] = concat(char(34), [Incident_ServiceOrder_Parts_Reservations].[Batch], char(34)),
	 [StorageLocationDescription] = concat(char(34), [Incident_ServiceOrder_Parts_Reservations].[StorageLocationDescription], char(34)),
	 [ReturnStorageLocation] = concat(char(34), [Incident_ServiceOrder_Parts_Reservations].[ReturnStorageLocation], char(34)),
	 [ReturnStorageLocationDescription] = concat(char(34), [Incident_ServiceOrder_Parts_Reservations].[ReturnStorageLocationDescription], char(34)),
	 [ReservationDateTIme] = convert(varchar(50), [Incident_ServiceOrder_Parts_Reservations].[ReservationDateTIme], 21),
	 [FieldReportCompleteDateTime] = convert(varchar(50), [Incident_ServiceOrder_Parts_Reservations].[FieldReportCompleteDateTime], 21)
from Ticketing.dbo.Incident_ServiceOrder_Parts_Reservations