select
	 [IncidentSlaID] = concat(char(34), [Incident_SLA].[IncidentSlaID], char(34)),
	 [IncidentID] = concat(char(34), [Incident_SLA].[IncidentID], char(34)),
	 [SlaTermID] = concat(char(34), [Incident_SLA].[SlaTermID], char(34)),
	 [SlaCallProfileID] = concat(char(34), [Incident_SLA].[SlaCallProfileID], char(34)),
	 [SlaServiceProfileID] = concat(char(34), [Incident_SLA].[SlaServiceProfileID], char(34)),
	 [SlaStartTime] = convert(varchar(50), [Incident_SLA].[SlaStartTime], 21),
	 [SlaDeadline] = convert(varchar(50), [Incident_SLA].[SlaDeadline], 21),
	 [SlaStatus] = concat(char(34), [Incident_SLA].[SlaStatus], char(34)),
	 [SlaTotalTimeDurationAllowed_Minutes] = concat(char(34), [Incident_SLA].[SlaTotalTimeDurationAllowed_Minutes], char(34)),
	 [SlaTimeDurationForClosedActivities_Minutes] = concat(char(34), [Incident_SLA].[SlaTimeDurationForClosedActivities_Minutes], char(34)),
	 [SlaDisposition] = concat(char(34), [Incident_SLA].[SlaDisposition], char(34)),
	 [SlaDispositionDeterminationDateTime] = convert(varchar(50), [Incident_SLA].[SlaDispositionDeterminationDateTime], 21),
	 [SlaRequiredTravelStartTime] = convert(varchar(50), [Incident_SLA].[SlaRequiredTravelStartTime], 21),
	 [SlaJeopordyStartTime] = convert(varchar(50), [Incident_SLA].[SlaJeopordyStartTime], 21),
	 [SlaServiceCommitment] = concat(char(34), [Incident_SLA].[SlaServiceCommitment], char(34)),
	 [SlaAcceptanceDateTime] = convert(varchar(50), [Incident_SLA].[SlaAcceptanceDateTime], 21),
	 [SlaTimeZoneKey] = concat(char(34), [Incident_SLA].[SlaTimeZoneKey], char(34)),
	 [SlaDisposition_Actual] = concat(char(34), [Incident_SLA].[SlaDisposition_Actual], char(34))
from Ticketing.dbo.Incident_SLA