select
	 [BOMGuid] = quotename([tqoBOM].[BOMGuid], char(34)),
	 [ItemGuid] = quotename([tqoBOM].[ItemGuid], char(34)),
	 [ParentID] = quotename([tqoBOM].[ParentID], char(34)),
	 [EvenCountFlag] = quotename([tqoBOM].[EvenCountFlag], char(34)),
	 [MinQty] = quotename([tqoBOM].[MinQty], char(34)),
	 [MaxQty] = quotename([tqoBOM].[MaxQty], char(34)),
	 [StandardQty] = quotename([tqoBOM].[StandardQty], char(34)),
	 [StandardFlag] = quotename([tqoBOM].[StandardFlag], char(34)),
	 [RootItemGuid] = quotename([tqoBOM].[RootItemGuid], char(34)),
	 [MASCompKey] = quotename([tqoBOM].[MASCompKey], char(34)),
	 [MASParentKey] = quotename([tqoBOM].[MASParentKey], char(34)),
	 [ChangedByID] = quotename([tqoBOM].[ChangedByID], char(34)),
	 [LastChanged] = convert(varchar(50), [tqoBOM].[LastChanged], 21),
	 [CreateByID] = quotename([tqoBOM].[CreateByID], char(34)),
	 [CreateDate] = convert(varchar(50), [tqoBOM].[CreateDate], 21),
	 [Source] = quotename([tqoBOM].[Source], char(34)),
	 [SourceFKID] = quotename([tqoBOM].[SourceFKID], char(34)),
	 [SparesKit] = quotename([tqoBOM].[SparesKit], char(34)),
	 [SourceProc] = quotename([tqoBOM].[SourceProc], char(34)),
	 [FromSiteAudit] = quotename([tqoBOM].[FromSiteAudit], char(34))
from SinglePoint.dbo.tqoBOM