select
	 [UnitGuid] = quotename([tqoUnit].[UnitGuid], char(34)),
	 [CustomerID] = quotename([tqoUnit].[CustomerID], char(34)),
	 [BOMGuid] = quotename([tqoUnit].[BOMGuid], char(34)),
	 [BillToCustAddrGuid] = quotename([tqoUnit].[BillToCustAddrGuid], char(34)),
	 [ShipToCustAddrGuid] = quotename([tqoUnit].[ShipToCustAddrGuid], char(34)),
	 [MASSrvDealer] = quotename([tqoUnit].[MASSrvDealer], char(34)),
	 [MASUnitStatKey] = quotename([tqoUnit].[MASUnitStatKey], char(34)),
	 [HwPO_UserFld1] = quotename([tqoUnit].[HwPO_UserFld1], char(34)),
	 [HwPOLine_UserFld2] = quotename([tqoUnit].[HwPOLine_UserFld2], char(34)),
	 [SwSupportVendors_UserFld3] = quotename([tqoUnit].[SwSupportVendors_UserFld3], char(34)),
	 [SwPO_UserFld4] = quotename([tqoUnit].[SwPO_UserFld4], char(34)),
	 [SwPOLine_UserFld5] = quotename([tqoUnit].[SwPOLine_UserFld5], char(34)),
	 [ChangedByID] = quotename([tqoUnit].[ChangedByID], char(34)),
	 [LastChanged] = convert(varchar(50), [tqoUnit].[LastChanged], 21),
	 [CreateByID] = quotename([tqoUnit].[CreateByID], char(34)),
	 [CreateDate] = convert(varchar(50), [tqoUnit].[CreateDate], 21),
	 [TopSerialNum] = quotename([tqoUnit].[TopSerialNum], char(34)),
	 [TopShortDesc] = quotename([tqoUnit].[TopShortDesc], char(34)),
	 [NodeName] = quotename([tqoUnit].[NodeName], char(34)),
	 [PrevUnitGuid] = quotename([tqoUnit].[PrevUnitGuid], char(34)),
	 [MASUnitKey] = quotename([tqoUnit].[MASUnitKey], char(34)),
	 [WebModelCodeID] = quotename([tqoUnit].[WebModelCodeID], char(34)),
	 [WebModelCode] = quotename([tqoUnit].[WebModelCode], char(34)),
	 [FromAssetHeaderID] = quotename([tqoUnit].[FromAssetHeaderID], char(34)),
	 [RecSource] = quotename([tqoUnit].[RecSource], char(34))
from SinglePoint.dbo.tqoUnit