select
	 [IncidentSlaID] = concat('"', [Incident_SLA].[IncidentSlaID], '"'),
	 [IncidentID] = concat('"', [Incident_SLA].[IncidentID], '"'),
	 [SlaTermID] = concat('"', [Incident_SLA].[SlaTermID], '"'),
	 [SlaCallProfileID] = concat('"', [Incident_SLA].[SlaCallProfileID], '"'),
	 [SlaServiceProfileID] = concat('"', [Incident_SLA].[SlaServiceProfileID], '"'),
	 [SlaStartTime] = convert(varchar(50), [Incident_SLA].[SlaStartTime], 21),
	 [SlaDeadline] = convert(varchar(50), [Incident_SLA].[SlaDeadline], 21),
	 [SlaStatus] = concat('"', [Incident_SLA].[SlaStatus], '"'),
	 [SlaTotalTimeDurationAllowed_Minutes] = concat('"', [Incident_SLA].[SlaTotalTimeDurationAllowed_Minutes], '"'),
	 [SlaTimeDurationForClosedActivities_Minutes] = concat('"', [Incident_SLA].[SlaTimeDurationForClosedActivities_Minutes], '"'),
	 [SlaDisposition] = concat('"', [Incident_SLA].[SlaDisposition], '"'),
	 [SlaDispositionDeterminationDateTime] = convert(varchar(50), [Incident_SLA].[SlaDispositionDeterminationDateTime], 21),
	 [SlaRequiredTravelStartTime] = convert(varchar(50), [Incident_SLA].[SlaRequiredTravelStartTime], 21),
	 [SlaJeopordyStartTime] = convert(varchar(50), [Incident_SLA].[SlaJeopordyStartTime], 21),
	 [SlaServiceCommitment] = concat('"', [Incident_SLA].[SlaServiceCommitment], '"'),
	 [SlaAcceptanceDateTime] = convert(varchar(50), [Incident_SLA].[SlaAcceptanceDateTime], 21),
	 [SlaTimeZoneKey] = concat('"', [Incident_SLA].[SlaTimeZoneKey], '"'),
	 [SlaDisposition_Actual] = concat('"', [Incident_SLA].[SlaDisposition_Actual], '"')
from Ticketing.dbo.Incident_SLA