select
	 [BUKRS] = quotename([BUKRS], char(34)),
	 [BELNR] = quotename([BELNR], char(34)),
	 [BUZEI] = quotename([BUZEI], char(34)),
	 [GJAHR] = quotename([GJAHR], char(34)),
	 [HKONT] = quotename([HKONT], char(34)),
	 [ZUONR] = quotename([ZUONR], char(34)),
	 [BUDAT] = quotename([BUDAT], char(34)),
	 [BLDAT] = quotename([BLDAT], char(34)),
	 [WAERS] = quotename([WAERS], char(34)),
	 [XBLNR] = quotename([XBLNR], char(34)),
	 [BLART] = quotename([BLART], char(34)),
	 [BSCHL] = quotename([BSCHL], char(34)),
	 [SHKZG] = quotename([SHKZG], char(34)),
	 [SGTXT] = quotename([SGTXT], char(34)),
	 [AUFNR] = quotename([AUFNR], char(34)),
	 [WERKS] = quotename([WERKS], char(34)),
	 [KOSTL] = quotename([KOSTL], char(34)),
	 [PSWSL] = quotename([PSWSL], char(34)),
	 [PRCTR] = quotename([PRCTR], char(34)),
	 [XSTOV] = quotename([XSTOV], char(34))
from SAP_Production.dbo.BSIS_BSAS_LC