select
	 [MANDT] = quotename([MANDT], char(34)),
	 [PLVAR] = quotename([PLVAR], char(34)),
	 [OTYPE] = quotename([OTYPE], char(34)),
	 [OBJID] = quotename([OBJID], char(34)),
	 [ISTAT] = quotename([ISTAT], char(34)),
	 [BEGDA] = convert(varchar(50), [BEGDA], 21),
	 [ENDDA] = convert(varchar(50), [ENDDA], 21),
	 [LANGU] = quotename([LANGU], char(34)),
	 [SEQNR] = quotename([SEQNR], char(34)),
	 [OTJID] = quotename([OTJID], char(34)),
	 [INFTY] = quotename([INFTY], char(34)),
	 [AEDTM] = convert(varchar(50), [AEDTM], 21),
	 [UNAME] = quotename([UNAME], char(34)),
	 [REASN] = quotename([REASN], char(34)),
	 [HISTO] = quotename([HISTO], char(34)),
	 [ITXNR] = quotename([ITXNR], char(34)),
	 [SHORT] = quotename([SHORT], char(34)),
	 [STEXT] = quotename([STEXT], char(34)),
	 [GDATE] = convert(varchar(50), [GDATE], 21),
	 [MC_SHORT] = quotename([MC_SHORT], char(34)),
	 [MC_STEXT] = quotename([MC_STEXT], char(34)),
	 [MC_SEARK] = quotename([MC_SEARK], char(34)),
	 [ETL_DATA_SOURCE] = quotename([ETL_DATA_SOURCE], char(34)),
	 [ETL_PROCESS_ID] = quotename([ETL_PROCESS_ID], char(34)),
	 [ETL_LOAD_DATE] = convert(varchar(50), [ETL_LOAD_DATE], 21)
from SAP_Production.dbo.HRP1000