select
	 [MANDT] = quotename(IHPA.[MANDT], char(34)),
	 [OBJNR] = quotename(IHPA.[OBJNR], char(34)),
	 [PARVW] = quotename(IHPA.[PARVW], char(34)),
	 [COUNTER] = quotename(IHPA.[COUNTER], char(34)),
	 [OBTYP] = quotename(IHPA.[OBTYP], char(34)),
	 [PARNR] = quotename(IHPA.[PARNR], char(34)),
	 [INHER] = quotename(IHPA.[INHER], char(34)),
	 [ERDAT] = convert(varchar(50), IHPA.[ERDAT], 21),
	 [ERZEIT] = quotename(IHPA.[ERZEIT], char(34)),
	 [ERNAM] = quotename(IHPA.[ERNAM], char(34)),
	 [AEDAT] = convert(varchar(50), IHPA.[AEDAT], 21),
	 [AEZEIT] = quotename(IHPA.[AEZEIT], char(34)),
	 [AENAM] = quotename(IHPA.[AENAM], char(34)),
	 [KZLOESCH] = quotename(IHPA.[KZLOESCH], char(34)),
	 [ADRNR] = quotename(IHPA.[ADRNR], char(34)),
	 [TZONSP] = quotename(IHPA.[TZONSP], char(34)),
	 [ETL_DATA_SOURCE] = quotename(IHPA.[ETL_DATA_SOURCE], char(34)),
	 [ETL_PROCESS_ID] = quotename(IHPA.[ETL_PROCESS_ID], char(34)),
	 [ETL_LOAD_DATE] = convert(varchar(50), IHPA.[ETL_LOAD_DATE], 21)
from SAP_Production.dbo.IHPA