select
	 [MANDT] = quotename([MANDT], char(34)),
	 [OBJNR] = quotename([OBJNR], char(34)),
	 [PARVW] = quotename([PARVW], char(34)),
	 [COUNTER] = quotename([COUNTER], char(34)),
	 [OBTYP] = quotename([OBTYP], char(34)),
	 [PARNR] = quotename([PARNR], char(34)),
	 [INHER] = quotename([INHER], char(34)),
	 [ERDAT] = convert(varchar(50), [ERDAT], 21),
	 [ERZEIT] = quotename([ERZEIT], char(34)),
	 [ERNAM] = quotename([ERNAM], char(34)),
	 [AEDAT] = convert(varchar(50), [AEDAT], 21),
	 [AEZEIT] = quotename([AEZEIT], char(34)),
	 [AENAM] = quotename([AENAM], char(34)),
	 [KZLOESCH] = quotename([KZLOESCH], char(34)),
	 [ADRNR] = quotename([ADRNR], char(34)),
	 [TZONSP] = quotename([TZONSP], char(34)),
	 [ETL_DATA_SOURCE] = quotename([ETL_DATA_SOURCE], char(34)),
	 [ETL_PROCESS_ID] = quotename([ETL_PROCESS_ID], char(34)),
	 [ETL_LOAD_DATE] = convert(varchar(50), [ETL_LOAD_DATE], 21)
from SAP_Production.dbo.IHPA