select
	 [MANDT] = quotename(OBJK.[MANDT], char(34)),
	 [OBKNR] = quotename(OBJK.[OBKNR], char(34)),
	 [OBZAE] = quotename(OBJK.[OBZAE], char(34)),
	 [EQUNR] = quotename(OBJK.[EQUNR], char(34)),
	 [IHNUM] = quotename(OBJK.[IHNUM], char(34)),
	 [BAUTL] = quotename(OBJK.[BAUTL], char(34)),
	 [ILOAN] = quotename(OBJK.[ILOAN], char(34)),
	 [SORTF] = quotename(OBJK.[SORTF], char(34)),
	 [BEARB] = quotename(OBJK.[BEARB], char(34)),
	 [OBJVW] = quotename(OBJK.[OBJVW], char(34)),
	 [SERNR] = quotename(OBJK.[SERNR], char(34)),
	 [MATNR] = quotename(OBJK.[MATNR], char(34)),
	 [DATUM] = convert(varchar(50), OBJK.[DATUM], 21),
	 [EQSNR] = quotename(OBJK.[EQSNR], char(34)),
	 [TASER] = quotename(OBJK.[TASER], char(34)),
	 [UII] = quotename(OBJK.[UII], char(34)),
	 [ETL_DATA_SOURCE] = quotename(OBJK.[ETL_DATA_SOURCE], char(34)),
	 [ETL_PROCESS_ID] = quotename(OBJK.[ETL_PROCESS_ID], char(34)),
	 [ETL_LOAD_DATE] = convert(varchar(50), OBJK.[ETL_LOAD_DATE], 21)
from SAP_Production.dbo.OBJK