select
	 [MANDT] = quotename([MANDT], char(34)),
	 [OBJNR] = quotename([OBJNR], char(34)),
	 [VKORG] = quotename([VKORG], char(34)),
	 [VTWEG] = quotename([VTWEG], char(34)),
	 [SPART] = quotename([SPART], char(34)),
	 [VKGRP] = quotename([VKGRP], char(34)),
	 [VKBUR] = quotename([VKBUR], char(34)),
	 [BSTKD] = quotename([BSTKD], char(34)),
	 [BSTDK] = quotename([BSTDK], char(34)),
	 [MATNR] = quotename([MATNR], char(34)),
	 [MENGE] = quotename([MENGE], char(34)),
	 [MEINS] = quotename([MEINS], char(34)),
	 [CUOBJ] = quotename([CUOBJ], char(34)),
	 [FFPRF] = quotename([FFPRF], char(34)),
	 [FAKTF] = quotename([FAKTF], char(34)),
	 [ETL_DATA_SOURCE] = quotename([ETL_DATA_SOURCE], char(34)),
	 [ETL_PROCESS_ID] = quotename([ETL_PROCESS_ID], char(34)),
	 [ETL_LOAD_DATE] = quotename([ETL_LOAD_DATE], char(34))
from SAP_Production.dbo.PMSDO