select
	 [MANDT] = concat(char(34), replace(cast([SER03].[MANDT] as nvarchar(3)), char(34), char(0)), char(34)),
	 [OBKNR] = cast([SER03].[OBKNR] as varchar(36)),
	 [MBLNR] = concat(char(34), replace(cast([SER03].[MBLNR] as nvarchar(10)), char(34), char(0)), char(34)),
	 [MJAHR] = concat(char(34), replace(cast([SER03].[MJAHR] as nvarchar(4)), char(34), char(0)), char(34)),
	 [ZEILE] = concat(char(34), replace(cast([SER03].[ZEILE] as nvarchar(4)), char(34), char(0)), char(34)),
	 [BLART] = concat(char(34), replace(cast([SER03].[BLART] as nvarchar(2)), char(34), char(0)), char(34)),
	 [BWART] = concat(char(34), replace(cast([SER03].[BWART] as nvarchar(3)), char(34), char(0)), char(34)),
	 [SHKZG] = concat(char(34), replace(cast([SER03].[SHKZG] as nvarchar(1)), char(34), char(0)), char(34)),
	 [DATUM] = concat(char(34), replace(cast([SER03].[DATUM] as nvarchar(8)), char(34), char(0)), char(34)),
	 [UZEIT] = concat(char(34), replace(cast([SER03].[UZEIT] as nvarchar(6)), char(34), char(0)), char(34)),
	 [LETZNR] = concat(char(34), replace(cast([SER03].[LETZNR] as nvarchar(4)), char(34), char(0)), char(34)),
	 [ANZSN] = cast([SER03].[ANZSN] as varchar(36)),
	 [VORGANG] = concat(char(34), replace(cast([SER03].[VORGANG] as nvarchar(4)), char(34), char(0)), char(34)),
	 [LIEFERANT] = concat(char(34), replace(cast([SER03].[LIEFERANT] as nvarchar(10)), char(34), char(0)), char(34)),
	 [KUNDE] = concat(char(34), replace(cast([SER03].[KUNDE] as nvarchar(10)), char(34), char(0)), char(34)),
	 [WERK] = concat(char(34), replace(cast([SER03].[WERK] as nvarchar(4)), char(34), char(0)), char(34)),
	 [LAGERORT] = concat(char(34), replace(cast([SER03].[LAGERORT] as nvarchar(4)), char(34), char(0)), char(34)),
	 [CHARGE] = concat(char(34), replace(cast([SER03].[CHARGE] as nvarchar(10)), char(34), char(0)), char(34))
from SAP_REPO.dbo.SER03