select
	 [MANDT] = quotename([MANDT], char(34)),
	 [OBKNR] = quotename([OBKNR], char(34)),
	 [SDAUFNR] = quotename([SDAUFNR], char(34)),
	 [POSNR] = quotename([POSNR], char(34)),
	 [DATUM] = convert(varchar(50), [DATUM], 21),
	 [LETZNR] = quotename([LETZNR], char(34)),
	 [KUNDE] = quotename([KUNDE], char(34)),
	 [ANZSN] = quotename([ANZSN], char(34)),
	 [VORGANG] = quotename([VORGANG], char(34)),
	 [VBTYP] = quotename([VBTYP], char(34)),
	 [SD_AUART] = quotename([SD_AUART], char(34)),
	 [SD_POSTYP] = quotename([SD_POSTYP], char(34)),
	 [VKORG] = quotename([VKORG], char(34)),
	 [VTWEG] = quotename([VTWEG], char(34)),
	 [SPART] = quotename([SPART], char(34)),
	 [LTSPS] = quotename([LTSPS], char(34)),
	 [UII] = quotename([UII], char(34)),
	 [ETL_DATA_SOURCE] = quotename([ETL_DATA_SOURCE], char(34)),
	 [ETL_PROCESS_ID] = quotename([ETL_PROCESS_ID], char(34)),
	 [ETL_LOAD_DATE] = convert(varchar(50), [ETL_LOAD_DATE], 21)
from SAP_Production.dbo.SER02