select
	 [CLIENT] = quotename([CLIENT], char(34)),
	 [AUART] = quotename([AUART], char(34)),
	 [AUTYP] = quotename([AUTYP], char(34)),
	 [NUMKR] = quotename([NUMKR], char(34)),
	 [OBLIGO] = quotename([OBLIGO], char(34)),
	 [ERLOESE] = quotename([ERLOESE], char(34)),
	 [STSMA] = quotename([STSMA], char(34)),
	 [APROF] = quotename([APROF], char(34)),
	 [PPROF] = quotename([PPROF], char(34)),
	 [COPAR] = quotename([COPAR], char(34)),
	 [RESZ1] = quotename([RESZ1], char(34)),
	 [RESZ2] = quotename([RESZ2], char(34)),
	 [AUFKL] = quotename([AUFKL], char(34)),
	 [RELKZ] = quotename([RELKZ], char(34)),
	 [CHGKZ] = quotename([CHGKZ], char(34)),
	 [BPROF] = quotename([BPROF], char(34)),
	 [PLINT] = quotename([PLINT], char(34)),
	 [NABPF] = quotename([NABPF], char(34)),
	 [VORPL] = quotename([VORPL], char(34)),
	 [LAYOUT] = quotename([LAYOUT], char(34)),
	 [TDFORM] = quotename([TDFORM], char(34)),
	 [SCOPE] = quotename([SCOPE], char(34)),
	 [COLORDPROC] = quotename([COLORDPROC], char(34)),
	 [VRG_STSMA] = quotename([VRG_STSMA], char(34)),
	 [FUNC_AREA] = quotename([FUNC_AREA], char(34)),
	 [EXEC_PROFILE] = quotename([EXEC_PROFILE], char(34))
from SAP_Production.dbo.T003O