select
	 [CLIENT] = isNull(quotename([CLIENT], char(34)), '\N'),
	 [AUART] = isNull(quotename([AUART], char(34)), '\N'),
	 [AUTYP] = isNull(quotename([AUTYP], char(34)), '\N'),
	 [NUMKR] = isNull(quotename([NUMKR], char(34)), '\N'),
	 [OBLIGO] = isNull(quotename([OBLIGO], char(34)), '\N'),
	 [ERLOESE] = isNull(quotename([ERLOESE], char(34)), '\N'),
	 [STSMA] = isNull(quotename([STSMA], char(34)), '\N'),
	 [APROF] = isNull(quotename([APROF], char(34)), '\N'),
	 [PPROF] = isNull(quotename([PPROF], char(34)), '\N'),
	 [COPAR] = isNull(quotename([COPAR], char(34)), '\N'),
	 [RESZ1] = isNull(quotename([RESZ1], char(34)), '\N'),
	 [RESZ2] = isNull(quotename([RESZ2], char(34)), '\N'),
	 [AUFKL] = isNull(quotename([AUFKL], char(34)), '\N'),
	 [RELKZ] = isNull(quotename([RELKZ], char(34)), '\N'),
	 [CHGKZ] = isNull(quotename([CHGKZ], char(34)), '\N'),
	 [BPROF] = isNull(quotename([BPROF], char(34)), '\N'),
	 [PLINT] = isNull(quotename([PLINT], char(34)), '\N'),
	 [NABPF] = isNull(quotename([NABPF], char(34)), '\N'),
	 [VORPL] = isNull(quotename([VORPL], char(34)), '\N'),
	 [LAYOUT] = isNull(quotename([LAYOUT], char(34)), '\N'),
	 [TDFORM] = isNull(quotename([TDFORM], char(34)), '\N'),
	 [SCOPE] = isNull(quotename([SCOPE], char(34)), '\N'),
	 [COLORDPROC] = isNull(quotename([COLORDPROC], char(34)), '\N'),
	 [VRG_STSMA] = isNull(quotename([VRG_STSMA], char(34)), '\N'),
	 [FUNC_AREA] = isNull(quotename([FUNC_AREA], char(34)), '\N'),
	 [EXEC_PROFILE] = isNull(quotename([EXEC_PROFILE], char(34)), '\N')
from SAP_Production.dbo.T003O