select
	 [CLIENT] = quotename([T003O].[CLIENT], char(34)),
	 [AUART] = quotename([T003O].[AUART], char(34)),
	 [AUTYP] = quotename([T003O].[AUTYP], char(34)),
	 [NUMKR] = quotename([T003O].[NUMKR], char(34)),
	 [OBLIGO] = quotename([T003O].[OBLIGO], char(34)),
	 [ERLOESE] = quotename([T003O].[ERLOESE], char(34)),
	 [STSMA] = quotename([T003O].[STSMA], char(34)),
	 [APROF] = quotename([T003O].[APROF], char(34)),
	 [PPROF] = quotename([T003O].[PPROF], char(34)),
	 [COPAR] = quotename([T003O].[COPAR], char(34)),
	 [RESZ1] = quotename([T003O].[RESZ1], char(34)),
	 [RESZ2] = quotename([T003O].[RESZ2], char(34)),
	 [AUFKL] = quotename([T003O].[AUFKL], char(34)),
	 [RELKZ] = quotename([T003O].[RELKZ], char(34)),
	 [CHGKZ] = quotename([T003O].[CHGKZ], char(34)),
	 [BPROF] = quotename([T003O].[BPROF], char(34)),
	 [PLINT] = quotename([T003O].[PLINT], char(34)),
	 [NABPF] = quotename([T003O].[NABPF], char(34)),
	 [VORPL] = quotename([T003O].[VORPL], char(34)),
	 [LAYOUT] = quotename([T003O].[LAYOUT], char(34)),
	 [TDFORM] = quotename([T003O].[TDFORM], char(34)),
	 [SCOPE] = quotename([T003O].[SCOPE], char(34)),
	 [COLORDPROC] = quotename([T003O].[COLORDPROC], char(34)),
	 [VRG_STSMA] = quotename([T003O].[VRG_STSMA], char(34)),
	 [FUNC_AREA] = quotename([T003O].[FUNC_AREA], char(34)),
	 [EXEC_PROFILE] = quotename([T003O].[EXEC_PROFILE], char(34))
from SAP_Production.dbo.T003O