select
	 [MANDT] = concat(char(34), replace(cast([VBPA].[MANDT] as nvarchar(3)), char(34), char(0)), char(34)),
	 [VBELN] = concat(char(34), replace(cast([VBPA].[VBELN] as nvarchar(10)), char(34), char(0)), char(34)),
	 [POSNR] = concat(char(34), replace(cast([VBPA].[POSNR] as nvarchar(6)), char(34), char(0)), char(34)),
	 [PARVW] = concat(char(34), replace(cast([VBPA].[PARVW] as nvarchar(2)), char(34), char(0)), char(34)),
	 [KUNNR] = concat(char(34), replace(cast([VBPA].[KUNNR] as nvarchar(10)), char(34), char(0)), char(34)),
	 [LIFNR] = concat(char(34), replace(cast([VBPA].[LIFNR] as nvarchar(10)), char(34), char(0)), char(34)),
	 [PERNR] = concat(char(34), replace(cast([VBPA].[PERNR] as nvarchar(8)), char(34), char(0)), char(34)),
	 [PARNR] = concat(char(34), replace(cast([VBPA].[PARNR] as nvarchar(10)), char(34), char(0)), char(34)),
	 [ADRNR] = concat(char(34), replace(cast([VBPA].[ADRNR] as nvarchar(10)), char(34), char(0)), char(34)),
	 [ABLAD] = concat(char(34), replace(cast([VBPA].[ABLAD] as nvarchar(25)), char(34), char(0)), char(34)),
	 [LAND1] = concat(char(34), replace(cast([VBPA].[LAND1] as nvarchar(3)), char(34), char(0)), char(34)),
	 [ADRDA] = concat(char(34), replace(cast([VBPA].[ADRDA] as nvarchar(1)), char(34), char(0)), char(34)),
	 [XCPDK] = concat(char(34), replace(cast([VBPA].[XCPDK] as nvarchar(1)), char(34), char(0)), char(34)),
	 [HITYP] = concat(char(34), replace(cast([VBPA].[HITYP] as nvarchar(1)), char(34), char(0)), char(34)),
	 [PRFRE] = concat(char(34), replace(cast([VBPA].[PRFRE] as nvarchar(1)), char(34), char(0)), char(34)),
	 [BOKRE] = concat(char(34), replace(cast([VBPA].[BOKRE] as nvarchar(1)), char(34), char(0)), char(34)),
	 [HISTUNR] = concat(char(34), replace(cast([VBPA].[HISTUNR] as nvarchar(2)), char(34), char(0)), char(34)),
	 [KNREF] = concat(char(34), replace(cast([VBPA].[KNREF] as nvarchar(30)), char(34), char(0)), char(34)),
	 [LZONE] = concat(char(34), replace(cast([VBPA].[LZONE] as nvarchar(10)), char(34), char(0)), char(34)),
	 [HZUOR] = concat(char(34), replace(cast([VBPA].[HZUOR] as nvarchar(2)), char(34), char(0)), char(34)),
	 [STCEG] = concat(char(34), replace(cast([VBPA].[STCEG] as nvarchar(20)), char(34), char(0)), char(34)),
	 [PARVW_FF] = concat(char(34), replace(cast([VBPA].[PARVW_FF] as nvarchar(1)), char(34), char(0)), char(34)),
	 [ADRNP] = concat(char(34), replace(cast([VBPA].[ADRNP] as nvarchar(10)), char(34), char(0)), char(34)),
	 [KALE] = concat(char(34), replace(cast([VBPA].[KALE] as nvarchar(1)), char(34), char(0)), char(34))
from SAP_REPO.dbo.VBPA